'use strict';

(() => {
  const OPS_API = 'https://lmztoiikbgcaeztdweov.supabase.co/functions/v1/job-board-ops-api';
  const SUITE_VIEW_KEY = 'rf_job_board_suite_view';
  const HOT_PREFIX = 'HOT-WORKER-';
  const DAY = 86400000;
  const HOUR = 3600000;
  const suite = { events: [], meta: [], view: localStorage.getItem(SUITE_VIEW_KEY) || '', loading: false };

  Object.assign(I18N.ro, {
    suite_attention: 'Necesită atenție', suite_history: 'Istoric / Analytics',
    suite_command_jobs: 'JOBURI ACTIVE', suite_command_free: 'POZIȚII LIBERE', suite_command_seconds: 'SECONDS ACTIVI', suite_command_attention: 'NECESITĂ ATENȚIE', suite_command_hot: 'HOT WORKERS',
    suite_command_jobs_hint: 'OPEN + CLAIMED acum', suite_command_free_hint: 'Necesar încă nepreluat', suite_command_seconds_hint: 'Recruiteri cu responsabilități', suite_command_attention_hint: 'Joburi cu semnale de risc', suite_command_hot_hint: 'Disponibili în ultimele 24h',
    suite_attention_title: 'Needs Attention — ce trebuie rezolvat acum', suite_attention_subtitle: 'Prioritizează joburile blocate, urgente, cu start apropiat, acoperire slabă sau date incomplete.',
    suite_health: 'HEALTH', suite_ai_next: 'AI NEXT ACTION', suite_view_job: 'Vezi jobul', suite_no_attention: 'Totul arată sănătos acum. Nu există joburi care necesită intervenție imediată.',
    flag_urgent: 'Urgent', flag_no_claim: 'Fără recruiter', flag_free: '{count} locuri libere', flag_start_soon: 'Start apropiat', flag_stale: 'Claim fără update', flag_overload: 'Second supraîncărcat', flag_no_rate: 'Rate lipsă', flag_no_location: 'Locație lipsă', flag_no_postcode: 'Postcode lipsă', flag_past_start: 'Data start trecută', flag_duplicate: 'Posibil duplicat',
    action_assign: 'Pune un recruiter pe job acum.', action_add_seconds: 'Mai sunt {count} poziții libere. Adaugă acoperire fără să supraîncarci recruiterii existenți.', action_request_update: 'Cere update de la {name}; claim-ul nu a fost actualizat recent.', action_fix_rate: 'First-ul ar trebui să confirme sau să adauge rata înainte de următorul claim.', action_fix_details: 'Completează datele esențiale ale jobului ca recruiterii să poată decide mai repede.', action_start_soon: 'Startul este foarte aproape. Prioritizează acest job înaintea celor cu termen mai larg.', action_rebalance: 'Redistribuie o parte din locuri: cel puțin un Second lucrează deja pe mai multe joburi.', action_healthy: 'Acoperirea este sănătoasă. Păstrează echipa actuală și urmărește progresul.',
    activity_title: 'Activitate live', activity_hint: 'Ultimele acțiuni din Job Board', activity_created: 'a postat jobul', activity_claimed: 'a făcut claim', activity_filled: 'a confirmat muncitori', activity_released: 'a eliberat locuri', activity_edited: 'a editat jobul', activity_closed: 'a închis jobul', activity_reopened: 'a redeschis jobul', activity_claim_update: 'a actualizat confidence/deadline', activity_generic: 'a actualizat jobul',
    workload_title: 'Workload', workload_one: 'Focus bun: 1 job activ', workload_two: '2 joburi active — atenție la focus', workload_many: '{count} joburi active — supraîncărcat',
    first_perf_fill: 'FILL RATE', first_perf_response: 'PRIMUL CLAIM', first_perf_total: 'JOBURI TOTAL', first_perf_active: 'ACTIVE',
    notify_title: 'Notificări', notify_mark_seen: 'Marchează văzute', notify_none: 'Nicio notificare nouă.', notify_first_claim: '{name} a făcut claim pe jobul tău: {trade}.', notify_job_changed: 'Jobul {trade} pe care lucrezi a fost actualizat de First.', notify_deadline: 'Deadline-ul tău de update pentru {trade} a trecut.',
    plan_button: 'Update plan', plan_title: 'Confidence + deadline', plan_intro: 'Spune First-ului cât de sigur ești și până când dai următorul update.', plan_confidence: 'Confidence', plan_high: 'High confidence', plan_medium: 'Medium', plan_trying: 'Trying', plan_deadline: 'Următorul update', plan_1h: 'în 1 oră', plan_2h: 'în 2 ore', plan_4h: 'în 4 ore', plan_today: 'azi, final program', plan_note: 'Notă scurtă', plan_save: 'Salvează planul', plan_saved: 'Planul de claim a fost actualizat.', plan_due: 'update {time}', plan_overdue: 'UPDATE ÎNTÂRZIAT',
    history_title: 'Istoric și Analytics', history_subtitle: 'Joburile finalizate sau închise sunt separate de operaționalul live.', history_filled: 'FINALIZATE', history_closed: 'ÎNCHISE', history_positions: 'POZIȚII GĂSITE', history_rate: 'FILL RATE', history_first: 'FIRST', history_status: 'STATUS', history_date: 'DATA', history_none: 'Nu există încă istoric.',
    hot_match_title: '✨ AI Match — Hot Worker → Job', hot_match_hint: 'Potrivire după meserie, postcode/locație și poziții libere.', hot_match_assign: 'Atribuie', hot_match_none: 'Niciun job activ potrivit pentru acest Hot Worker.',
    quality_title: 'Quality flags',
  });

  Object.assign(I18N.en, {
    suite_attention: 'Needs attention', suite_history: 'History / Analytics',
    suite_command_jobs: 'ACTIVE JOBS', suite_command_free: 'FREE POSITIONS', suite_command_seconds: 'ACTIVE SECONDS', suite_command_attention: 'NEEDS ATTENTION', suite_command_hot: 'HOT WORKERS',
    suite_command_jobs_hint: 'OPEN + CLAIMED now', suite_command_free_hint: 'Requirement not yet claimed', suite_command_seconds_hint: 'Recruiters with active responsibility', suite_command_attention_hint: 'Jobs with risk signals', suite_command_hot_hint: 'Available in the last 24h',
    suite_attention_title: 'Needs Attention — what to fix now', suite_attention_subtitle: 'Prioritize blocked or urgent jobs, imminent starts, weak coverage and incomplete data.',
    suite_health: 'HEALTH', suite_ai_next: 'AI NEXT ACTION', suite_view_job: 'View job', suite_no_attention: 'Everything looks healthy. No job needs immediate intervention.',
    flag_urgent: 'Urgent', flag_no_claim: 'No recruiter', flag_free: '{count} free slots', flag_start_soon: 'Starts soon', flag_stale: 'Claim needs update', flag_overload: 'Recruiter overloaded', flag_no_rate: 'Rate missing', flag_no_location: 'Location missing', flag_no_postcode: 'Postcode missing', flag_past_start: 'Start date passed', flag_duplicate: 'Possible duplicate',
    action_assign: 'Put a recruiter on this job now.', action_add_seconds: '{count} positions are still free. Add coverage without overloading current recruiters.', action_request_update: 'Ask {name} for an update; this claim has not been updated recently.', action_fix_rate: 'The First should confirm or add the rate before the next claim.', action_fix_details: 'Complete the essential job data so recruiters can decide faster.', action_start_soon: 'The start is very close. Prioritize this job over work with a wider deadline.', action_rebalance: 'Rebalance some slots: at least one recruiter is already working multiple jobs.', action_healthy: 'Coverage looks healthy. Keep the current team and monitor progress.',
    activity_title: 'Live activity', activity_hint: 'Latest Job Board actions', activity_created: 'posted the job', activity_claimed: 'claimed the job', activity_filled: 'confirmed workers', activity_released: 'released slots', activity_edited: 'edited the job', activity_closed: 'closed the job', activity_reopened: 'reopened the job', activity_claim_update: 'updated confidence/deadline', activity_generic: 'updated the job',
    workload_title: 'Workload', workload_one: 'Good focus: 1 active job', workload_two: '2 active jobs — watch focus', workload_many: '{count} active jobs — overloaded',
    first_perf_fill: 'FILL RATE', first_perf_response: 'FIRST CLAIM', first_perf_total: 'TOTAL JOBS', first_perf_active: 'ACTIVE',
    notify_title: 'Notifications', notify_mark_seen: 'Mark seen', notify_none: 'No new notifications.', notify_first_claim: '{name} claimed your job: {trade}.', notify_job_changed: 'The {trade} job you are working on was updated by the First.', notify_deadline: 'Your update deadline for {trade} has passed.',
    plan_button: 'Update plan', plan_title: 'Confidence + deadline', plan_intro: 'Tell the First how confident you are and when you will give the next update.', plan_confidence: 'Confidence', plan_high: 'High confidence', plan_medium: 'Medium', plan_trying: 'Trying', plan_deadline: 'Next update', plan_1h: 'in 1 hour', plan_2h: 'in 2 hours', plan_4h: 'in 4 hours', plan_today: 'end of today', plan_note: 'Short note', plan_save: 'Save plan', plan_saved: 'Claim plan updated.', plan_due: 'update {time}', plan_overdue: 'UPDATE OVERDUE',
    history_title: 'History and Analytics', history_subtitle: 'Filled and closed jobs are kept separate from the live operation.', history_filled: 'FILLED', history_closed: 'CLOSED', history_positions: 'WORKERS FOUND', history_rate: 'FILL RATE', history_first: 'FIRST', history_status: 'STATUS', history_date: 'DATE', history_none: 'No history yet.',
    hot_match_title: '✨ AI Match — Hot Worker → Job', hot_match_hint: 'Matched by trade, postcode/location and free positions.', hot_match_assign: 'Assign', hot_match_none: 'No active job is a good match for this Hot Worker.',
    quality_title: 'Quality flags',
  });

  const workspace = $('.workspace');
  const switcher = $('.transparency-switcher');
  const jobsGrid = $('#jobsGrid');
  if (!workspace || !switcher || !jobsGrid) return;

  const attentionButton = document.createElement('button');
  attentionButton.type = 'button'; attentionButton.className = 'transparency-tab suite-attention-tab'; attentionButton.dataset.suiteView = 'attention';
  attentionButton.innerHTML = `<span>⚠ </span><span data-i18n="suite_attention">Necesită atenție</span><span class="tab-count" id="suiteAttentionCount">0</span>`;
  switcher.append(attentionButton);
  const historyButton = document.createElement('button');
  historyButton.type = 'button'; historyButton.className = 'transparency-tab suite-history-tab'; historyButton.dataset.suiteView = 'history';
  historyButton.innerHTML = `<span>◷ </span><span data-i18n="suite_history">Istoric / Analytics</span><span class="tab-count" id="suiteHistoryCount">0</span>`;
  switcher.append(historyButton);

  const command = document.createElement('section');
  command.className = 'suite-command-center';
  command.innerHTML = `
    <button class="suite-command-card" data-suite-nav="jobs"><strong id="suiteActiveJobs">0</strong><span data-i18n="suite_command_jobs">JOBURI ACTIVE</span><small data-i18n="suite_command_jobs_hint"></small></button>
    <button class="suite-command-card" data-suite-nav="jobs"><strong id="suiteFreePositions">0</strong><span data-i18n="suite_command_free">POZIȚII LIBERE</span><small data-i18n="suite_command_free_hint"></small></button>
    <button class="suite-command-card seconds" data-suite-nav="seconds"><strong id="suiteActiveSeconds">0</strong><span data-i18n="suite_command_seconds">SECONDS ACTIVI</span><small data-i18n="suite_command_seconds_hint"></small></button>
    <button class="suite-command-card attention" data-suite-nav="attention"><strong id="suiteAttentionTop">0</strong><span data-i18n="suite_command_attention">NECESITĂ ATENȚIE</span><small data-i18n="suite_command_attention_hint"></small></button>
    <button class="suite-command-card hot" data-suite-nav="hot"><strong id="suiteHotCount">0</strong><span data-i18n="suite_command_hot">HOT WORKERS</span><small data-i18n="suite_command_hot_hint"></small></button>`;
  const opsStrip = $('#opsKpiStrip') || switcher;
  opsStrip.before(command);

  const attentionDashboard = document.createElement('section'); attentionDashboard.id = 'suiteAttentionDashboard'; attentionDashboard.className = 'suite-dashboard transparency-hidden';
  const historyDashboard = document.createElement('section'); historyDashboard.id = 'suiteHistoryDashboard'; historyDashboard.className = 'suite-dashboard transparency-hidden';
  const anchor = $('#recommendationDashboard') || $('#secondDashboard') || $('#firstDashboard') || jobsGrid;
  anchor.after(attentionDashboard, historyDashboard);

  const activity = document.createElement('details'); activity.className = 'suite-activity'; activity.open = false;
  activity.innerHTML = `<summary><span>● <span data-i18n="activity_title">Activitate live</span></span><small data-i18n="activity_hint">Ultimele acțiuni din Job Board</small></summary><div id="suiteActivityList" class="suite-activity-list"></div>`;
  command.after(activity);

  const notifyButton = document.createElement('button'); notifyButton.type = 'button'; notifyButton.className = 'suite-notify-button'; notifyButton.innerHTML = `🔔<span id="suiteNotifyCount" class="suite-notify-count" hidden>0</span>`;
  $('.top-actions')?.insertBefore(notifyButton, $('.post-action-stack') || $('#addButton'));
  const notifyPanel = document.createElement('aside'); notifyPanel.id = 'suiteNotificationPanel'; notifyPanel.className = 'suite-notification-panel'; notifyPanel.hidden = true;
  notifyPanel.innerHTML = `<div class="suite-notification-head"><h3 data-i18n="notify_title">Notificări</h3><button id="suiteMarkSeen" type="button" data-i18n="notify_mark_seen">Marchează văzute</button></div><div id="suiteNotificationList" class="suite-notification-list"></div>`;
  document.body.append(notifyPanel);

  document.body.insertAdjacentHTML('beforeend', `
    <dialog id="suitePlanDialog" class="suite-plan-dialog small-dialog">
      <form id="suitePlanForm" class="dialog-form">
        <button class="dialog-close" type="button" id="suitePlanClose">×</button>
        <span class="eyebrow dark">CLAIM PLAN</span><h2 data-i18n="plan_title">Confidence + deadline</h2><p data-i18n="plan_intro"></p>
        <input id="suitePlanJobId" type="hidden">
        <label><span data-i18n="plan_confidence">Confidence</span></label>
        <div class="suite-plan-options">
          <label><input type="radio" name="suiteConfidence" value="high"><span data-i18n="plan_high">High confidence</span></label>
          <label><input type="radio" name="suiteConfidence" value="medium" checked><span data-i18n="plan_medium">Medium</span></label>
          <label><input type="radio" name="suiteConfidence" value="trying"><span data-i18n="plan_trying">Trying</span></label>
        </div>
        <label><span data-i18n="plan_deadline">Următorul update</span><select id="suitePlanDue"><option value="1" data-i18n="plan_1h">în 1 oră</option><option value="2" data-i18n="plan_2h">în 2 ore</option><option value="4" data-i18n="plan_4h">în 4 ore</option><option value="today" data-i18n="plan_today">azi, final program</option></select></label>
        <label><span data-i18n="plan_note">Notă scurtă</span><textarea id="suitePlanNote" rows="3" maxlength="1000"></textarea></label>
        <div class="form-actions"><button class="ghost" id="suitePlanCancel" type="button" data-i18n="cancel">Renunță</button><button class="primary" type="submit" data-i18n="plan_save">Salvează planul</button></div>
      </form>
    </dialog>`);

  const baseRender = render;
  const baseApplyLanguage = applyLanguage;

  function isHot(job){ return String(job?.job_reference || '').startsWith(HOT_PREFIX); }
  function isOperational(job){ return job && job.source_kind !== 'import' && !isHot(job); }
  function activeJobs(){ return state.jobs.filter((j)=>isOperational(j)&&['open','claimed'].includes(j.status)); }
  function hotWorkers(){ const now=Date.now(); return state.jobs.filter((j)=>isHot(j)&&j.status!=='closed'&&now-new Date(j.created_at).getTime()<DAY); }
  function claims(job){ return Array.isArray(job?.claims)?job.claims:[]; }
  function totals(job){ const c=claims(job); const total=Math.max(1,Number(job.workers_needed)||1); const claimed=Number.isFinite(Number(job.workers_claimed))?Number(job.workers_claimed):c.reduce((s,x)=>s+(Number(x.quantity_claimed)||0),0); const found=Number.isFinite(Number(job.workers_filled))?Number(job.workers_filled):c.reduce((s,x)=>s+(Number(x.quantity_filled)||0),0); return {total,claimed,found,free:Math.max(total-claimed,0)}; }
  function activeClaim(claim){ return Math.max((Number(claim.quantity_claimed)||0)-(Number(claim.quantity_filled)||0),0)>0; }
  function activeClaimRows(){ const out=[]; activeJobs().forEach(job=>claims(job).forEach(claim=>{if(activeClaim(claim))out.push({job,claim});})); return out; }
  function agentJobCount(name){ const key=normalizeName(name); return new Set(activeClaimRows().filter(r=>normalizeName(r.claim.agent_name)===key).map(r=>r.job.id)).size; }
  function metaFor(jobId,agent){ return suite.meta.find(m=>Number(m.job_id)===Number(jobId)&&normalizeName(m.agent_name)===normalizeName(agent))||null; }
  function parseHot(job){ try{const p=JSON.parse(job.source_text||'{}'); if(p?.kind==='hot_worker')return p;}catch{} return {ref:job.job_reference||'Worker',notes:job.description||''}; }

  async function opsFetch(action,payload={}){
    const r=await fetch(OPS_API,{method:'POST',headers:{'Content-Type':'application/json',apikey:PUBLISHABLE_KEY},body:JSON.stringify({action,...payload})});
    const d=await r.json().catch(()=>({})); if(!r.ok||d.ok===false)throw new Error(d.error||`Ops ${r.status}`); return d;
  }
  async function refreshOps(){ if(suite.loading)return; suite.loading=true; try{const d=await opsFetch('snapshot');suite.events=Array.isArray(d.events)?d.events:[];suite.meta=Array.isArray(d.claim_meta)?d.claim_meta:[]; renderSuiteDecorations();}catch(e){console.warn('Ops snapshot',e);}finally{suite.loading=false;} }

  function duplicate(job){ const key=[normalizeName(job.trade),normalizeName(job.location),String(job.postcode||'').replace(/\s/g,'').toUpperCase()].join('|'); if(!key.replace(/\|/g,''))return false; return activeJobs().some(other=>other.id!==job.id&&[normalizeName(other.trade),normalizeName(other.location),String(other.postcode||'').replace(/\s/g,'').toUpperCase()].join('|')===key); }
  function startDays(job){ if(!job.start_date)return null; const d=new Date(`${job.start_date}T12:00:00`); return Number.isNaN(d.getTime())?null:(d.getTime()-Date.now())/DAY; }
  function staleClaim(job){ const row=claims(job).filter(activeClaim).map(c=>({c,m:metaFor(job.id,c.agent_name)})).sort((a,b)=>new Date(a.m?.last_update_at||a.c.updated_at||a.c.created_at)-new Date(b.m?.last_update_at||b.c.updated_at||b.c.created_at))[0]; if(!row)return null; const when=new Date(row.m?.last_update_at||row.c.updated_at||row.c.created_at).getTime(); return Date.now()-when>4*HOUR?row.c:null; }
  function overloaded(job){ return claims(job).filter(activeClaim).find(c=>agentJobCount(c.agent_name)>1)||null; }
  function flags(job){ const x=[]; const total=totals(job); const days=startDays(job); const stale=staleClaim(job); const over=overloaded(job); if(job.priority==='urgent')x.push({key:'flag_urgent',level:'red'}); if(claims(job).filter(activeClaim).length===0&&total.free>0)x.push({key:'flag_no_claim',level:'red'}); if(total.free>0)x.push({key:'flag_free',values:{count:total.free},level:total.free>=3?'red':'yellow'}); if(days!==null&&days>=-1&&days<=1)x.push({key:'flag_start_soon',level:'red'}); if(stale)x.push({key:'flag_stale',level:'yellow'}); if(over)x.push({key:'flag_overload',level:'yellow'}); if(!job.rate)x.push({key:'flag_no_rate',level:'yellow'}); if(!job.location)x.push({key:'flag_no_location',level:'yellow'}); if(!job.postcode)x.push({key:'flag_no_postcode',level:'yellow'}); if(days!==null&&days<-1)x.push({key:'flag_past_start',level:'red'}); if(duplicate(job))x.push({key:'flag_duplicate',level:'yellow'}); return x; }
  function health(job){ let s=100; flags(job).forEach(f=>{s-=f.level==='red'?18:9;}); const t=totals(job); if(t.found>0)s+=Math.min(10,t.found*2); return Math.max(15,Math.min(100,s)); }
  function nextAction(job){ const t0=totals(job); const c=claims(job).filter(activeClaim); const stale=staleClaim(job); const over=overloaded(job); const days=startDays(job); if(c.length===0&&t0.free>0)return t('action_assign'); if(stale)return t('action_request_update',{name:stale.agent_name}); if(over)return t('action_rebalance'); if(!job.rate)return t('action_fix_rate'); if((!job.location&&!job.postcode)||!job.trade)return t('action_fix_details'); if(days!==null&&days>=-1&&days<=1&&t0.free>0)return t('action_start_soon'); if(t0.free>0)return t('action_add_seconds',{count:t0.free}); return t('action_healthy'); }
  function attentionJobs(){ return activeJobs().map(job=>({job,flags:flags(job),health:health(job)})).filter(x=>x.flags.length||x.health<85).sort((a,b)=>a.health-b.health||new Date(b.job.created_at)-new Date(a.job.created_at)); }

  function renderCommand(){ const active=activeJobs(); const free=active.reduce((s,j)=>s+totals(j).free,0); const seconds=new Set(activeClaimRows().map(r=>normalizeName(r.claim.agent_name)).filter(Boolean)).size; const att=attentionJobs().length; $('#suiteActiveJobs').textContent=active.length;$('#suiteFreePositions').textContent=free;$('#suiteActiveSeconds').textContent=seconds;$('#suiteAttentionTop').textContent=att;$('#suiteHotCount').textContent=hotWorkers().length;$('#suiteAttentionCount').textContent=att;$('#suiteHistoryCount').textContent=state.jobs.filter(j=>isOperational(j)&&['filled','closed'].includes(j.status)).length; }

  function attentionCard(x){ const {job}=x; const cls=x.health<55?'red':x.health<78?'yellow':'green'; const place=[job.location,job.postcode].filter(Boolean).join(' · ')||t('location_unspecified'); return `<article class="suite-attention-card ${cls}"><div class="suite-attention-top"><div class="suite-health"><div class="suite-health-score">${x.health}</div><span>${escapeHtml(t('suite_health'))}</span></div><span class="badge badge-${escapeHtml(job.status)}">${escapeHtml(String(job.status).toUpperCase())}</span></div><h4>${escapeHtml(job.trade)}</h4><div class="suite-place">⌖ ${escapeHtml(place)}</div><div class="suite-first">First: <b>${escapeHtml(job.created_by||t('unknown'))}</b></div><div class="suite-flags">${x.flags.map(f=>`<span class="suite-flag ${f.level}">${escapeHtml(t(f.key,f.values||{}))}</span>`).join('')}</div><div class="suite-ai-action"><strong>✨ ${escapeHtml(t('suite_ai_next'))}</strong><span>${escapeHtml(nextAction(job))}</span></div><div class="suite-attention-actions"><button type="button" data-suite-open-job="${job.id}">${escapeHtml(t('suite_view_job'))}</button></div></article>`; }
  function renderAttention(){ const list=attentionJobs(); attentionDashboard.innerHTML=`<div class="suite-head"><div><h3>${escapeHtml(t('suite_attention_title'))}</h3><p>${escapeHtml(t('suite_attention_subtitle'))}</p></div></div>${list.length?`<div class="suite-attention-grid">${list.map(attentionCard).join('')}</div>`:`<div class="recommend-empty">${escapeHtml(t('suite_no_attention'))}</div>`}`; }

  function eventText(e){ const map={created:'activity_created',claimed:'activity_claimed',filled:'activity_filled',released:'activity_released',edited:'activity_edited',closed:'activity_closed',reopened:'activity_reopened',claim_update:'activity_claim_update'}; return t(map[e.action]||'activity_generic'); }
  function activityIcon(a){return a==='created'?'＋':a==='filled'?'✓':a==='closed'?'×':a==='released'?'↩':a==='claim_update'?'◷':'↗';}
  function renderActivity(){ const list=$('#suiteActivityList'); if(!list)return; const jobMap=new Map(state.jobs.map(j=>[Number(j.id),j])); const events=suite.events.filter(e=>{const j=jobMap.get(Number(e.job_id));return j&&isOperational(j);}).slice(0,12); list.innerHTML=events.length?events.map(e=>{const j=jobMap.get(Number(e.job_id));return `<div class="suite-activity-row"><div class="suite-activity-icon">${activityIcon(e.action)}</div><div class="suite-activity-copy"><strong>${escapeHtml(e.agent_name||t('unknown'))} ${escapeHtml(eventText(e))}</strong><span>${escapeHtml(j?.trade||'Job')} · First: ${escapeHtml(j?.created_by||t('unknown'))}</span></div><span class="suite-activity-time">${escapeHtml(relativeTime(e.created_at))}</span></div>`;}).join(''):`<div class="recommend-empty">—</div>`; }

  function avgFirstClaim(firstJobs){ const vals=[]; firstJobs.forEach(j=>{const cs=claims(j).map(c=>new Date(c.created_at).getTime()).filter(Number.isFinite); if(cs.length){const delta=Math.min(...cs)-new Date(j.created_at).getTime();if(delta>=0)vals.push(delta);}}); if(!vals.length)return '—'; const m=vals.reduce((a,b)=>a+b,0)/vals.length; return m<HOUR?`${Math.round(m/60000)}m`:`${(m/HOUR).toFixed(1)}h`; }
  function decorateFirsts(){ $$('.first-card').forEach(card=>{card.querySelector('.suite-first-performance')?.remove(); const name=card.querySelector('.first-name-row h4')?.textContent?.trim(); if(!name)return; const all=state.jobs.filter(j=>isOperational(j)&&normalizeName(j.created_by)===normalizeName(name)); const active=all.filter(j=>['open','claimed'].includes(j.status)).length; const totalPositions=all.reduce((s,j)=>s+Math.max(1,Number(j.workers_needed)||1),0); const found=all.reduce((s,j)=>s+totals(j).found,0); const fill=totalPositions?Math.round(found/totalPositions*100):0; card.insertAdjacentHTML('beforeend',`<div class="suite-first-performance"><div><strong>${all.length}</strong><small>${escapeHtml(t('first_perf_total'))}</small></div><div><strong>${active}</strong><small>${escapeHtml(t('first_perf_active'))}</small></div><div><strong>${fill}%</strong><small>${escapeHtml(t('first_perf_fill'))}</small></div><div><strong>${escapeHtml(avgFirstClaim(all))}</strong><small>${escapeHtml(t('first_perf_response'))}</small></div></div>`); }); }
  function decorateSeconds(){ $$('.second-card').forEach(card=>{card.querySelector('.suite-workload')?.remove();const name=card.querySelector('.second-name-row h4')?.textContent?.trim();if(!name)return;const count=agentJobCount(name);const cls=count>=3?'over':count===2?'warn':'';const msg=count<=1?t('workload_one'):count===2?t('workload_two'):t('workload_many',{count});card.querySelector('.second-card-head')?.insertAdjacentHTML('beforeend',`<div class="suite-workload ${cls}"><div class="suite-workload-head"><span>${escapeHtml(t('workload_title'))}</span><strong>${count}/1</strong></div><div class="suite-workload-meter">${[1,2,3,4].map(i=>`<i class="${i<=Math.min(count,4)?'on':''}"></i>`).join('')}</div><small>${escapeHtml(msg)}</small></div>`);}); }

  function metaLabel(m){ if(!m)return ''; const due=m.update_due_at?new Date(m.update_due_at):null; const overdue=due&&due.getTime()<Date.now(); const label=m.confidence==='high'?t('plan_high'):m.confidence==='trying'?t('plan_trying'):t('plan_medium'); const dueText=due?(overdue?t('plan_overdue'):t('plan_due',{time:relativeTime(due)})):''; return `<span class="suite-meta-badge ${escapeHtml(m.confidence)} ${overdue?'suite-deadline-over':''}">${escapeHtml(label)}${dueText?` · ${escapeHtml(dueText)}`:''}</span>`; }
  function decorateClaimMeta(){ $$('.job-card[data-job-id]').forEach(card=>{card.querySelector('.suite-claim-meta')?.remove();const job=state.jobs.find(j=>Number(j.id)===Number(card.dataset.jobId));if(!job||!isOperational(job))return;const active=claims(job).filter(activeClaim);if(!active.length)return;const rows=active.map(c=>{const m=metaFor(job.id,c.agent_name);const mine=isSameAgent(c.agent_name);return `<div><strong>${escapeHtml(c.agent_name)}</strong>${metaLabel(m)}${mine?` <button class="suite-plan-button" type="button" data-suite-plan="${job.id}">${escapeHtml(t('plan_button'))}</button>`:''}</div>`;}).join('');const box=`<div class="suite-claim-meta" style="display:grid;gap:6px;margin:8px 0 2px;font-size:10px">${rows}</div>`;const cap=card.querySelector('.worker-capacity'); if(cap)cap.insertAdjacentHTML('beforeend',box); else card.querySelector('.job-transparency')?.insertAdjacentHTML('beforeend',box);}); }

  function historyJobs(){return state.jobs.filter(j=>isOperational(j)&&['filled','closed'].includes(j.status)).sort((a,b)=>new Date(b.filled_at||b.closed_at||b.updated_at)-new Date(a.filled_at||a.closed_at||a.updated_at));}
  function renderHistory(){const list=historyJobs();const filled=list.filter(j=>j.status==='filled');const closed=list.filter(j=>j.status==='closed');const pos=filled.reduce((s,j)=>s+totals(j).found,0);const need=list.reduce((s,j)=>s+Math.max(1,Number(j.workers_needed)||1),0);const rate=need?Math.round(pos/need*100):0;historyDashboard.innerHTML=`<div class="suite-head"><div><h3>${escapeHtml(t('history_title'))}</h3><p>${escapeHtml(t('history_subtitle'))}</p></div></div><div class="suite-history-summary"><div><strong>${filled.length}</strong><small>${escapeHtml(t('history_filled'))}</small></div><div><strong>${closed.length}</strong><small>${escapeHtml(t('history_closed'))}</small></div><div><strong>${pos}</strong><small>${escapeHtml(t('history_positions'))}</small></div><div><strong>${rate}%</strong><small>${escapeHtml(t('history_rate'))}</small></div></div>${list.length?`<div class="suite-history-list">${list.slice(0,100).map(j=>`<div class="suite-history-row"><strong>${escapeHtml(j.trade)}</strong><span>${escapeHtml(j.created_by||t('unknown'))}</span><span>${escapeHtml(String(j.status).toUpperCase())}</span><span>${escapeHtml(formatDate(j.filled_at||j.closed_at||j.updated_at,{day:'2-digit',month:'short',year:'numeric'}))}</span></div>`).join('')}</div>`:`<div class="recommend-empty">${escapeHtml(t('history_none'))}</div>`}`;}

  function notifications(){ const out=[]; const seen=Number(localStorage.getItem(`rf_seen_${state.email||state.agent}`)||0); activeJobs().forEach(job=>{if(isSameAgent(job.created_by)){claims(job).forEach(c=>{const ts=new Date(c.created_at).getTime();if(ts>seen&&ts>Date.now()-2*DAY)out.push({ts,text:t('notify_first_claim',{name:c.agent_name,trade:job.trade})});});} const mine=claims(job).find(c=>isSameAgent(c.agent_name)); if(mine){const ju=new Date(job.updated_at||job.created_at).getTime();const cu=new Date(mine.updated_at||mine.created_at).getTime();if(ju>cu+60000&&ju>seen)out.push({ts:ju,text:t('notify_job_changed',{trade:job.trade})});const m=metaFor(job.id,mine.agent_name);if(m?.update_due_at&&new Date(m.update_due_at).getTime()<Date.now()&&new Date(m.update_due_at).getTime()>seen)out.push({ts:new Date(m.update_due_at).getTime(),text:t('notify_deadline',{trade:job.trade})});}});return out.sort((a,b)=>b.ts-a.ts);}
  function renderNotifications(){const n=notifications();const badge=$('#suiteNotifyCount');badge.textContent=n.length;badge.hidden=!n.length;$('#suiteNotificationList').innerHTML=n.length?n.map(x=>`<div class="suite-notification"><strong>${escapeHtml(x.text)}</strong><span>${escapeHtml(relativeTime(new Date(x.ts)))}</span></div>`).join(''):`<div class="suite-notification"><span>${escapeHtml(t('notify_none'))}</span></div>`;}

  function matchScore(worker,job){const wTrade=normalizeName(worker.trade),jTrade=normalizeName(job.trade);let score=0;if(wTrade&&jTrade){if(wTrade===jTrade)score+=65;else if(wTrade.includes(jTrade)||jTrade.includes(wTrade))score+=48;}const wp=String(worker.postcode||'').replace(/\s/g,'').toUpperCase(),jp=String(job.postcode||'').replace(/\s/g,'').toUpperCase();if(wp&&jp){if(wp===jp)score+=25;else if(wp.slice(0,3)===jp.slice(0,3))score+=18;else if(wp.slice(0,2)===jp.slice(0,2))score+=10;}const wl=normalizeName(worker.location),jl=normalizeName(job.location);if(wl&&jl&&(wl.includes(jl)||jl.includes(wl)))score+=15;if(totals(job).free>0)score+=Math.min(10,totals(job).free*2);if(job.priority==='urgent')score+=5;return Math.min(99,score);}
  function renderHotMatches(){const list=$('#hotWorkerList');if(!list)return;let panel=$('#suiteHotMatchPanel');if(!panel){panel=document.createElement('section');panel.id='suiteHotMatchPanel';panel.className='suite-hot-match-panel';list.after(panel);}const workers=hotWorkers();if(!workers.length){panel.innerHTML='';return;}panel.innerHTML=`<h4>${escapeHtml(t('hot_match_title'))}</h4><p style="margin:0;color:#7a8998;font-size:10px">${escapeHtml(t('hot_match_hint'))}</p>${workers.map(w=>{const data=parseHot(w);const matches=activeJobs().filter(j=>totals(j).free>0).map(j=>({j,score:matchScore(w,j)})).filter(x=>x.score>=45).sort((a,b)=>b.score-a.score).slice(0,3);return `<div class="suite-hot-match-worker"><strong>🔥 ${escapeHtml(data.ref||'Worker')} · ${escapeHtml(w.trade)}</strong>${matches.length?matches.map(x=>`<div class="suite-match-row"><div><b>${escapeHtml(x.j.trade)}</b><span> · First: ${escapeHtml(x.j.created_by||t('unknown'))}</span></div><div class="suite-match-score">${x.score}%</div><button type="button" data-suite-assign-hot="${x.j.id}" data-hot-ref="${escapeHtml(data.ref||'Worker')}">${escapeHtml(t('hot_match_assign'))}</button></div>`).join(''):`<div style="margin-top:7px;font-size:10px;color:#8b7a62">${escapeHtml(t('hot_match_none'))}</div>`}</div>`;}).join('')}`;}

  function hideSuitePanels(){ attentionDashboard.classList.add('transparency-hidden');historyDashboard.classList.add('transparency-hidden'); }
  function applySuiteView(){hideSuitePanels();$$('[data-suite-view]').forEach(b=>b.classList.toggle('is-active',b.dataset.suiteView===suite.view));if(!suite.view)return; const other=['#jobsGrid','#firstDashboard','#secondDashboard','#recommendationDashboard'].map(s=>$(s)).filter(Boolean);other.forEach(el=>el.classList.add('transparency-hidden'));$('.toolbar')?.classList.add('transparency-hidden');if(suite.view==='attention')attentionDashboard.classList.remove('transparency-hidden');if(suite.view==='history')historyDashboard.classList.remove('transparency-hidden');const h=$('.section-heading h2');if(h)h.textContent=suite.view==='attention'?t('suite_attention'):t('suite_history'); }

  function renderSuiteDecorations(){renderCommand();renderAttention();renderHistory();renderActivity();decorateFirsts();decorateSeconds();decorateClaimMeta();renderNotifications();if($('#hotWorkerDialog')?.open)renderHotMatches();applySuiteView();}
  render=function suiteRender(){baseRender();renderSuiteDecorations();};
  applyLanguage=function suiteApplyLanguage(){baseApplyLanguage();renderSuiteDecorations();};

  switcher.addEventListener('click',e=>{const suiteBtn=e.target.closest('[data-suite-view]');if(suiteBtn){suite.view=suiteBtn.dataset.suiteView;localStorage.setItem(SUITE_VIEW_KEY,suite.view);renderSuiteDecorations();return;}if(e.target.closest('button')){suite.view='';localStorage.removeItem(SUITE_VIEW_KEY);hideSuitePanels();}} ,true);
  command.addEventListener('click',e=>{const b=e.target.closest('[data-suite-nav]');if(!b)return;const v=b.dataset.suiteNav;if(v==='attention'){suite.view='attention';localStorage.setItem(SUITE_VIEW_KEY,'attention');renderSuiteDecorations();return;}if(v==='hot'){suite.view='';localStorage.removeItem(SUITE_VIEW_KEY);$('#hotWorkerButton')?.click();return;}suite.view='';localStorage.removeItem(SUITE_VIEW_KEY);const target=switcher.querySelector(v==='seconds'?'[data-ops-view="seconds"]':'[data-board-view="jobs"]');target?.click();});
  attentionDashboard.addEventListener('click',e=>{const b=e.target.closest('[data-suite-open-job]');if(!b)return;openJob(Number(b.dataset.suiteOpenJob));});
  historyDashboard.addEventListener('click',()=>{});

  function openJob(id){suite.view='';localStorage.removeItem(SUITE_VIEW_KEY);switcher.querySelector('[data-board-view="jobs"]')?.click();window.setTimeout(()=>{const card=document.querySelector(`.job-card[data-job-id="${id}"]`);card?.scrollIntoView({behavior:'smooth',block:'center'});card?.classList.add('recommend-highlight');window.setTimeout(()=>card?.classList.remove('recommend-highlight'),1800);},80);}

  notifyButton.addEventListener('click',()=>{notifyPanel.hidden=!notifyPanel.hidden;if(!notifyPanel.hidden)renderNotifications();});
  $('#suiteMarkSeen').addEventListener('click',()=>{localStorage.setItem(`rf_seen_${state.email||state.agent}`,String(Date.now()));renderNotifications();});

  document.addEventListener('click',e=>{const p=e.target.closest('[data-suite-plan]');if(p){openPlan(Number(p.dataset.suitePlan));return;}const a=e.target.closest('[data-suite-assign-hot]');if(a){const id=Number(a.dataset.suiteAssignHot);const ref=a.dataset.hotRef||'Hot Worker';$('#hotWorkerDialog')?.close();openJob(id);window.setTimeout(()=>{const card=document.querySelector(`.job-card[data-job-id="${id}"]`);const job=state.jobs.find(j=>Number(j.id)===id);const mine=job&&claims(job).find(c=>isSameAgent(c.agent_name)&&activeClaim(c));const btn=card?.querySelector(mine?'[data-action="found-slots"]':'[data-action="claim-slots"]');if(btn){btn.click();if(mine)window.setTimeout(()=>{if($('#foundNote'))$('#foundNote').value=`Hot Worker ${ref}`;},50);}},180);}});

  function openPlan(id){const job=state.jobs.find(j=>Number(j.id)===id);const claim=job&&claims(job).find(c=>isSameAgent(c.agent_name)&&activeClaim(c));if(!job||!claim)return;const m=metaFor(id,claim.agent_name);$('#suitePlanJobId').value=id;const val=m?.confidence||'medium';document.querySelector(`input[name="suiteConfidence"][value="${val}"]`)?.click();$('#suitePlanNote').value=m?.note||'';$('#suitePlanDue').value='2';$('#suitePlanDialog').showModal();}
  $('#suitePlanClose').addEventListener('click',()=>$('#suitePlanDialog').close());$('#suitePlanCancel').addEventListener('click',()=>$('#suitePlanDialog').close());
  $('#suitePlanForm').addEventListener('submit',async e=>{e.preventDefault();const id=Number($('#suitePlanJobId').value);const confidence=document.querySelector('input[name="suiteConfidence"]:checked')?.value||'medium';const dueVal=$('#suitePlanDue').value;let due;if(dueVal==='today'){due=new Date();due.setHours(18,0,0,0);if(due<Date.now())due.setDate(due.getDate()+1);}else due=new Date(Date.now()+Number(dueVal)*HOUR);try{setBusy(true,t('saving'));await opsFetch('set_claim_meta',{job_id:id,agent_name:state.agent,agent_email:state.email,confidence,update_due_at:due.toISOString(),note:$('#suitePlanNote').value.trim()});toast(t('plan_saved'),'success');$('#suitePlanDialog').close();await refreshOps();}catch(err){toast(err.message||t('network_error'),'error',5000);}finally{setBusy(false);}});

  const hotDialog=$('#hotWorkerDialog');if(hotDialog){hotDialog.addEventListener('toggle',renderHotMatches);const obs=new MutationObserver(()=>{if(hotDialog.open)renderHotMatches();});obs.observe($('#hotWorkerList'),{childList:true,subtree:true});}

  const observer=new MutationObserver(()=>{decorateFirsts();decorateSeconds();decorateClaimMeta();});observer.observe(workspace,{childList:true,subtree:true});
  window.setInterval(()=>{if(!document.hidden){refreshOps();renderSuiteDecorations();}},60000);
  applyLanguage();refreshOps();renderSuiteDecorations();
})();
