'use strict';

(() => {
  const OPS_API = 'https://lmztoiikbgcaeztdweov.supabase.co/functions/v1/job-board-ops-api';
  const VIEW_KEY = 'rf_job_board_suite_view';
  const HOT_PREFIX = 'HOT-WORKER-';
  const HOUR = 3600000;
  const DAY = 86400000;
  const suite = { events: [], meta: [], view: localStorage.getItem(VIEW_KEY) || '', loading: false };

  Object.assign(I18N.ro, {
    suite_attention:'Necesită atenție', suite_history:'Istoric / Analytics',
    suite_jobs:'JOBURI ACTIVE', suite_free:'POZIȚII LIBERE', suite_seconds:'SECONDS ACTIVI', suite_risk:'NECESITĂ ATENȚIE', suite_hot:'HOT WORKERS',
    suite_jobs_hint:'OPEN + CLAIMED acum', suite_free_hint:'Necesar încă nepreluat', suite_seconds_hint:'Recruiteri cu responsabilități', suite_risk_hint:'Joburi cu semnale de risc', suite_hot_hint:'Disponibili în ultimele 24h',
    attention_title:'Needs Attention — ce trebuie rezolvat acum', attention_subtitle:'Joburi urgente, blocate, cu start apropiat, acoperire slabă sau date incomplete.', no_attention:'Totul arată sănătos acum.',
    health:'HEALTH', ai_next:'AI NEXT ACTION', view_job:'Vezi jobul',
    flag_urgent:'Urgent', flag_no_claim:'Fără recruiter', flag_free:'{count} locuri libere', flag_start:'Start apropiat', flag_stale:'Claim fără update', flag_overload:'Second supraîncărcat', flag_rate:'Rate lipsă', flag_location:'Locație lipsă', flag_postcode:'Postcode lipsă', flag_past:'Start trecut', flag_duplicate:'Posibil duplicat',
    act_assign:'Pune un recruiter pe job acum.', act_more:'Mai sunt {count} poziții libere. Adaugă acoperire fără să supraîncarci recruiterii existenți.', act_update:'Cere update de la {name}; claim-ul nu a fost actualizat recent.', act_rate:'First-ul ar trebui să confirme sau să adauge rata.', act_details:'Completează datele esențiale ale jobului.', act_start:'Startul este foarte aproape. Prioritizează acest job azi.', act_rebalance:'Redistribuie locurile: un Second lucrează deja pe mai multe joburi.', act_ok:'Acoperirea este sănătoasă. Urmărește progresul.',
    activity:'Activitate live', activity_hint:'Ultimele acțiuni din Job Board', created:'a postat jobul', claimed:'a făcut claim', filled:'a confirmat muncitori', released:'a eliberat locuri', edited:'a editat jobul', closed:'a închis jobul', reopened:'a redeschis jobul', claim_update:'a actualizat planul', generic_action:'a actualizat jobul',
    workload:'Workload', workload_1:'Focus bun: 1 job activ', workload_2:'2 joburi active — atenție la focus', workload_n:'{count} joburi active — supraîncărcat',
    perf_fill:'FILL RATE', perf_response:'PRIMUL CLAIM', perf_total:'JOBURI TOTAL', perf_active:'ACTIVE',
    notify:'Notificări', seen:'Marchează văzute', notify_none:'Nicio notificare nouă.', notify_claim:'{name} a făcut claim pe jobul tău: {trade}.', notify_change:'Jobul {trade} pe care lucrezi a fost actualizat.', notify_due:'Deadline-ul tău de update pentru {trade} a trecut.',
    plan:'Update plan', plan_title:'Confidence + deadline', plan_intro:'Spune First-ului cât de sigur ești și până când dai următorul update.', confidence:'Confidence', high:'High confidence', medium:'Medium', trying:'Trying', next_update:'Următorul update', in1:'în 1 oră', in2:'în 2 ore', in4:'în 4 ore', today:'azi, final program', short_note:'Notă scurtă', save_plan:'Salvează planul', plan_saved:'Planul de claim a fost actualizat.', due:'update {time}', overdue:'UPDATE ÎNTÂRZIAT',
    history_title:'Istoric și Analytics', history_subtitle:'Joburile finalizate și închise sunt separate de operaționalul live.', h_filled:'FINALIZATE', h_closed:'ÎNCHISE', h_workers:'MUNCITORI GĂSIȚI', h_rate:'FILL RATE', history_none:'Nu există încă istoric.',
    hot_match:'✨ AI Match — Hot Worker → Job', hot_hint:'Potrivire după meserie, postcode/locație și poziții libere.', assign:'Atribuie', no_match:'Niciun job activ potrivit.',
  });
  Object.assign(I18N.en, {
    suite_attention:'Needs attention', suite_history:'History / Analytics',
    suite_jobs:'ACTIVE JOBS', suite_free:'FREE POSITIONS', suite_seconds:'ACTIVE SECONDS', suite_risk:'NEEDS ATTENTION', suite_hot:'HOT WORKERS',
    suite_jobs_hint:'OPEN + CLAIMED now', suite_free_hint:'Requirement not yet claimed', suite_seconds_hint:'Recruiters with active responsibility', suite_risk_hint:'Jobs with risk signals', suite_hot_hint:'Available in the last 24h',
    attention_title:'Needs Attention — what to fix now', attention_subtitle:'Urgent or blocked jobs, imminent starts, weak coverage and incomplete data.', no_attention:'Everything looks healthy right now.',
    health:'HEALTH', ai_next:'AI NEXT ACTION', view_job:'View job',
    flag_urgent:'Urgent', flag_no_claim:'No recruiter', flag_free:'{count} free slots', flag_start:'Starts soon', flag_stale:'Claim needs update', flag_overload:'Recruiter overloaded', flag_rate:'Rate missing', flag_location:'Location missing', flag_postcode:'Postcode missing', flag_past:'Start date passed', flag_duplicate:'Possible duplicate',
    act_assign:'Put a recruiter on this job now.', act_more:'{count} positions are still free. Add coverage without overloading current recruiters.', act_update:'Ask {name} for an update; this claim has not been updated recently.', act_rate:'The First should confirm or add the rate.', act_details:'Complete the essential job details.', act_start:'The start is very close. Prioritize this job today.', act_rebalance:'Rebalance slots: a recruiter is already working multiple jobs.', act_ok:'Coverage is healthy. Monitor progress.',
    activity:'Live activity', activity_hint:'Latest Job Board actions', created:'posted the job', claimed:'claimed the job', filled:'confirmed workers', released:'released slots', edited:'edited the job', closed:'closed the job', reopened:'reopened the job', claim_update:'updated the plan', generic_action:'updated the job',
    workload:'Workload', workload_1:'Good focus: 1 active job', workload_2:'2 active jobs — watch focus', workload_n:'{count} active jobs — overloaded',
    perf_fill:'FILL RATE', perf_response:'FIRST CLAIM', perf_total:'TOTAL JOBS', perf_active:'ACTIVE',
    notify:'Notifications', seen:'Mark seen', notify_none:'No new notifications.', notify_claim:'{name} claimed your job: {trade}.', notify_change:'The {trade} job you work on was updated.', notify_due:'Your update deadline for {trade} has passed.',
    plan:'Update plan', plan_title:'Confidence + deadline', plan_intro:'Tell the First how confident you are and when you will give the next update.', confidence:'Confidence', high:'High confidence', medium:'Medium', trying:'Trying', next_update:'Next update', in1:'in 1 hour', in2:'in 2 hours', in4:'in 4 hours', today:'end of today', short_note:'Short note', save_plan:'Save plan', plan_saved:'Claim plan updated.', due:'update {time}', overdue:'UPDATE OVERDUE',
    history_title:'History and Analytics', history_subtitle:'Filled and closed jobs stay separate from the live operation.', h_filled:'FILLED', h_closed:'CLOSED', h_workers:'WORKERS FOUND', h_rate:'FILL RATE', history_none:'No history yet.',
    hot_match:'✨ AI Match — Hot Worker → Job', hot_hint:'Matched by trade, postcode/location and free positions.', assign:'Assign', no_match:'No active matching job.',
  });

  const workspace = $('.workspace');
  const switcher = $('.transparency-switcher');
  const jobsGrid = $('#jobsGrid');
  if (!workspace || !switcher || !jobsGrid) return;

  switcher.insertAdjacentHTML('beforeend', `
    <button type="button" class="transparency-tab suite-attention-tab" data-suite-view="attention"><span>⚠ </span><span data-i18n="suite_attention">Necesită atenție</span><span class="tab-count" id="suiteAttentionCount">0</span></button>
    <button type="button" class="transparency-tab suite-history-tab" data-suite-view="history"><span>◷ </span><span data-i18n="suite_history">Istoric / Analytics</span><span class="tab-count" id="suiteHistoryCount">0</span></button>`);

  const command = document.createElement('section');
  command.className = 'suite-command-center';
  command.innerHTML = `
    <button class="suite-command-card" data-suite-nav="jobs"><strong id="suiteActiveJobs">0</strong><span data-i18n="suite_jobs">JOBURI ACTIVE</span><small data-i18n="suite_jobs_hint"></small></button>
    <button class="suite-command-card" data-suite-nav="jobs"><strong id="suiteFreePositions">0</strong><span data-i18n="suite_free">POZIȚII LIBERE</span><small data-i18n="suite_free_hint"></small></button>
    <button class="suite-command-card seconds" data-suite-nav="seconds"><strong id="suiteActiveSeconds">0</strong><span data-i18n="suite_seconds">SECONDS ACTIVI</span><small data-i18n="suite_seconds_hint"></small></button>
    <button class="suite-command-card attention" data-suite-nav="attention"><strong id="suiteAttentionTop">0</strong><span data-i18n="suite_risk">NECESITĂ ATENȚIE</span><small data-i18n="suite_risk_hint"></small></button>
    <button class="suite-command-card hot" data-suite-nav="hot"><strong id="suiteHotCount">0</strong><span data-i18n="suite_hot">HOT WORKERS</span><small data-i18n="suite_hot_hint"></small></button>`;
  ($('#opsKpiStrip') || switcher).before(command);

  const activity = document.createElement('details');
  activity.className = 'suite-activity';
  activity.innerHTML = `<summary><span>● <span data-i18n="activity">Activitate live</span></span><small data-i18n="activity_hint"></small></summary><div id="suiteActivityList" class="suite-activity-list"></div>`;
  command.after(activity);

  const attentionDashboard = document.createElement('section');
  attentionDashboard.id = 'suiteAttentionDashboard'; attentionDashboard.className = 'suite-dashboard transparency-hidden';
  const historyDashboard = document.createElement('section');
  historyDashboard.id = 'suiteHistoryDashboard'; historyDashboard.className = 'suite-dashboard transparency-hidden';
  ($('#recommendationDashboard') || $('#secondDashboard') || $('#firstDashboard') || jobsGrid).after(attentionDashboard, historyDashboard);

  const notifyButton = document.createElement('button');
  notifyButton.className = 'suite-notify-button'; notifyButton.type = 'button';
  notifyButton.innerHTML = `🔔<span id="suiteNotifyCount" class="suite-notify-count" hidden>0</span>`;
  $('.top-actions')?.insertBefore(notifyButton, $('.post-action-stack') || $('#addButton'));
  const notifyPanel = document.createElement('aside');
  notifyPanel.id = 'suiteNotificationPanel'; notifyPanel.className = 'suite-notification-panel'; notifyPanel.hidden = true;
  notifyPanel.innerHTML = `<div class="suite-notification-head"><h3 data-i18n="notify">Notificări</h3><button id="suiteMarkSeen" type="button" data-i18n="seen">Marchează văzute</button></div><div id="suiteNotificationList" class="suite-notification-list"></div>`;
  document.body.append(notifyPanel);

  document.body.insertAdjacentHTML('beforeend', `<dialog id="suitePlanDialog" class="suite-plan-dialog small-dialog"><form id="suitePlanForm" class="dialog-form"><button class="dialog-close" type="button" id="suitePlanClose">×</button><span class="eyebrow dark">CLAIM PLAN</span><h2 data-i18n="plan_title">Confidence + deadline</h2><p data-i18n="plan_intro"></p><input id="suitePlanJobId" type="hidden"><label><span data-i18n="confidence">Confidence</span></label><div class="suite-plan-options"><label><input type="radio" name="suiteConfidence" value="high"><span data-i18n="high">High confidence</span></label><label><input type="radio" name="suiteConfidence" value="medium" checked><span data-i18n="medium">Medium</span></label><label><input type="radio" name="suiteConfidence" value="trying"><span data-i18n="trying">Trying</span></label></div><label><span data-i18n="next_update">Următorul update</span><select id="suitePlanDue"><option value="1" data-i18n="in1">în 1 oră</option><option value="2" data-i18n="in2">în 2 ore</option><option value="4" data-i18n="in4">în 4 ore</option><option value="today" data-i18n="today">azi, final program</option></select></label><label><span data-i18n="short_note">Notă scurtă</span><textarea id="suitePlanNote" rows="3" maxlength="1000"></textarea></label><div class="form-actions"><button class="ghost" id="suitePlanCancel" type="button" data-i18n="cancel">Renunță</button><button class="primary" type="submit" data-i18n="save_plan">Salvează planul</button></div></form></dialog>`);

  const baseRender = render;
  const baseApplyLanguage = applyLanguage;
  const isHot = j => String(j?.job_reference || '').startsWith(HOT_PREFIX);
  const isOperational = j => j && j.source_kind !== 'import' && !isHot(j);
  const activeJobs = () => state.jobs.filter(j => isOperational(j) && ['open','claimed'].includes(j.status));
  const claimRows = j => Array.isArray(j?.claims) ? j.claims : [];
  const claimActive = c => Math.max((Number(c.quantity_claimed)||0)-(Number(c.quantity_filled)||0),0) > 0;
  const totals = j => { const c=claimRows(j), total=Math.max(1,Number(j.workers_needed)||1), claimed=Number.isFinite(Number(j.workers_claimed))?Number(j.workers_claimed):c.reduce((s,x)=>s+(Number(x.quantity_claimed)||0),0), found=Number.isFinite(Number(j.workers_filled))?Number(j.workers_filled):c.reduce((s,x)=>s+(Number(x.quantity_filled)||0),0); return {total,claimed,found,free:Math.max(total-claimed,0)}; };
  const activeClaimRows = () => activeJobs().flatMap(job => claimRows(job).filter(claimActive).map(claim => ({job,claim})));
  const agentJobCount = name => new Set(activeClaimRows().filter(x=>normalizeName(x.claim.agent_name)===normalizeName(name)).map(x=>x.job.id)).size;
  const metaFor = (jobId, agent) => suite.meta.find(m=>Number(m.job_id)===Number(jobId)&&normalizeName(m.agent_name)===normalizeName(agent)) || null;
  const hotWorkers = () => state.jobs.filter(j=>isHot(j)&&j.status!=='closed'&&Date.now()-new Date(j.created_at).getTime()<DAY);
  const parseHot = j => { try { const p=JSON.parse(j.source_text||'{}'); if(p?.kind==='hot_worker')return p; } catch {} return {ref:'Worker',notes:j.description||''}; };

  async function opsFetch(action,payload={}) { const r=await fetch(OPS_API,{method:'POST',headers:{'Content-Type':'application/json',apikey:PUBLISHABLE_KEY},body:JSON.stringify({action,...payload})}); const d=await r.json().catch(()=>({})); if(!r.ok||d.ok===false) throw new Error(d.error||`Ops ${r.status}`); return d; }
  async function refreshOps() { if(suite.loading)return; suite.loading=true; try { const d=await opsFetch('snapshot'); suite.events=Array.isArray(d.events)?d.events:[]; suite.meta=Array.isArray(d.claim_meta)?d.claim_meta:[]; decorateAll(); } catch(e){ console.warn('operations suite',e); } finally { suite.loading=false; } }

  function daysToStart(j){ if(!j.start_date)return null; const d=new Date(`${j.start_date}T12:00:00`); return Number.isNaN(d.getTime())?null:(d.getTime()-Date.now())/DAY; }
  function isDuplicate(j){ const key=[normalizeName(j.trade),normalizeName(j.location),String(j.postcode||'').replace(/\s/g,'').toUpperCase()].join('|'); if(!key.replace(/\|/g,''))return false; return activeJobs().some(o=>o.id!==j.id&&[normalizeName(o.trade),normalizeName(o.location),String(o.postcode||'').replace(/\s/g,'').toUpperCase()].join('|')===key); }
  function staleClaim(j){ return claimRows(j).filter(claimActive).find(c=>Date.now()-new Date(metaFor(j.id,c.agent_name)?.last_update_at||c.updated_at||c.created_at).getTime()>4*HOUR) || null; }
  function overloaded(j){ return claimRows(j).filter(claimActive).find(c=>agentJobCount(c.agent_name)>1)||null; }
  function flags(j){ const f=[],tt=totals(j),days=daysToStart(j); if(j.priority==='urgent')f.push(['flag_urgent','red']); if(!claimRows(j).some(claimActive)&&tt.free>0)f.push(['flag_no_claim','red']); if(tt.free>0)f.push(['flag_free',tt.free>=3?'red':'yellow',{count:tt.free}]); if(days!==null&&days>=-1&&days<=1)f.push(['flag_start','red']); if(staleClaim(j))f.push(['flag_stale','yellow']); if(overloaded(j))f.push(['flag_overload','yellow']); if(!j.rate)f.push(['flag_rate','yellow']); if(!j.location)f.push(['flag_location','yellow']); if(!j.postcode)f.push(['flag_postcode','yellow']); if(days!==null&&days<-1)f.push(['flag_past','red']); if(isDuplicate(j))f.push(['flag_duplicate','yellow']); return f; }
  function health(j){ let s=100; flags(j).forEach(x=>s-=x[1]==='red'?18:9); s+=Math.min(8,totals(j).found*2); return Math.max(15,Math.min(100,s)); }
  function nextAction(j){ const tt=totals(j), stale=staleClaim(j), over=overloaded(j), days=daysToStart(j); if(!claimRows(j).some(claimActive)&&tt.free>0)return t('act_assign'); if(stale)return t('act_update',{name:stale.agent_name}); if(over)return t('act_rebalance'); if(!j.rate)return t('act_rate'); if(!j.location&&!j.postcode)return t('act_details'); if(days!==null&&days>=-1&&days<=1&&tt.free>0)return t('act_start'); if(tt.free>0)return t('act_more',{count:tt.free}); return t('act_ok'); }
  const attentionJobs = () => activeJobs().map(job=>({job,flags:flags(job),health:health(job)})).filter(x=>x.flags.length||x.health<85).sort((a,b)=>a.health-b.health);

  function renderCommand(){ const active=activeJobs(), free=active.reduce((s,j)=>s+totals(j).free,0), seconds=new Set(activeClaimRows().map(x=>normalizeName(x.claim.agent_name)).filter(Boolean)).size, risk=attentionJobs().length, history=state.jobs.filter(j=>isOperational(j)&&['filled','closed'].includes(j.status)).length; $('#suiteActiveJobs').textContent=active.length; $('#suiteFreePositions').textContent=free; $('#suiteActiveSeconds').textContent=seconds; $('#suiteAttentionTop').textContent=risk; $('#suiteHotCount').textContent=hotWorkers().length; $('#suiteAttentionCount').textContent=risk; $('#suiteHistoryCount').textContent=history; }
  function renderAttention(){ const list=attentionJobs(); attentionDashboard.innerHTML=`<div class="suite-head"><div><h3>${escapeHtml(t('attention_title'))}</h3><p>${escapeHtml(t('attention_subtitle'))}</p></div></div>${list.length?`<div class="suite-attention-grid">${list.map(x=>{const j=x.job,cls=x.health<55?'red':x.health<78?'yellow':'green',place=[j.location,j.postcode].filter(Boolean).join(' · ')||t('location_unspecified');return `<article class="suite-attention-card ${cls}"><div class="suite-attention-top"><div class="suite-health"><div class="suite-health-score">${x.health}</div><span>${escapeHtml(t('health'))}</span></div><span class="badge badge-${escapeHtml(j.status)}">${escapeHtml(String(j.status).toUpperCase())}</span></div><h4>${escapeHtml(j.trade)}</h4><div class="suite-place">⌖ ${escapeHtml(place)}</div><div class="suite-first">First: <b>${escapeHtml(j.created_by||t('unknown'))}</b></div><div class="suite-flags">${x.flags.map(f=>`<span class="suite-flag ${f[1]}">${escapeHtml(t(f[0],f[2]||{}))}</span>`).join('')}</div><div class="suite-ai-action"><strong>✨ ${escapeHtml(t('ai_next'))}</strong><span>${escapeHtml(nextAction(j))}</span></div><div class="suite-attention-actions"><button type="button" data-suite-open-job="${j.id}">${escapeHtml(t('view_job'))}</button></div></article>`;}).join('')}</div>`:`<div class="recommend-empty">${escapeHtml(t('no_attention'))}</div>`}`; }

  function renderActivity(){ const map=new Map(state.jobs.map(j=>[Number(j.id),j])), actions={created:'created',claimed:'claimed',filled:'filled',released:'released',edited:'edited',closed:'closed',reopened:'reopened',claim_update:'claim_update'}; const ev=suite.events.filter(e=>{const j=map.get(Number(e.job_id));return j&&isOperational(j);}).slice(0,12); $('#suiteActivityList').innerHTML=ev.length?ev.map(e=>{const j=map.get(Number(e.job_id)), icon=e.action==='filled'?'✓':e.action==='created'?'＋':e.action==='closed'?'×':e.action==='released'?'↩':'↗'; return `<div class="suite-activity-row"><div class="suite-activity-icon">${icon}</div><div class="suite-activity-copy"><strong>${escapeHtml(e.agent_name||t('unknown'))} ${escapeHtml(t(actions[e.action]||'generic_action'))}</strong><span>${escapeHtml(j.trade)} · First: ${escapeHtml(j.created_by||t('unknown'))}</span></div><span class="suite-activity-time">${escapeHtml(relativeTime(e.created_at))}</span></div>`;}).join(''):'<div class="recommend-empty">—</div>'; }

  function avgFirstClaim(jobs){ const a=[]; jobs.forEach(j=>{const c=claimRows(j).map(x=>new Date(x.created_at).getTime()).filter(Number.isFinite);if(c.length){const d=Math.min(...c)-new Date(j.created_at).getTime();if(d>=0)a.push(d);}});if(!a.length)return '—';const n=a.reduce((s,x)=>s+x,0)/a.length;return n<HOUR?`${Math.round(n/60000)}m`:`${(n/HOUR).toFixed(1)}h`;}
  function decorateFirsts(){ $$('.first-card').forEach(card=>{if(card.querySelector('.suite-first-performance'))return;const name=card.querySelector('.first-name-row h4')?.textContent?.trim();if(!name)return;const all=state.jobs.filter(j=>isOperational(j)&&normalizeName(j.created_by)===normalizeName(name)),active=all.filter(j=>['open','claimed'].includes(j.status)).length,total=all.reduce((s,j)=>s+Math.max(1,Number(j.workers_needed)||1),0),found=all.reduce((s,j)=>s+totals(j).found,0),rate=total?Math.round(found/total*100):0;card.insertAdjacentHTML('beforeend',`<div class="suite-first-performance"><div><strong>${all.length}</strong><small>${escapeHtml(t('perf_total'))}</small></div><div><strong>${active}</strong><small>${escapeHtml(t('perf_active'))}</small></div><div><strong>${rate}%</strong><small>${escapeHtml(t('perf_fill'))}</small></div><div><strong>${escapeHtml(avgFirstClaim(all))}</strong><small>${escapeHtml(t('perf_response'))}</small></div></div>`);}); }
  function decorateSeconds(){ $$('.second-card').forEach(card=>{if(card.querySelector('.suite-workload'))return;const name=card.querySelector('.second-name-row h4')?.textContent?.trim();if(!name)return;const count=agentJobCount(name),cls=count>=3?'over':count===2?'warn':'',msg=count<=1?t('workload_1'):count===2?t('workload_2'):t('workload_n',{count});card.querySelector('.second-card-head')?.insertAdjacentHTML('beforeend',`<div class="suite-workload ${cls}"><div class="suite-workload-head"><span>${escapeHtml(t('workload'))}</span><strong>${count}/1</strong></div><div class="suite-workload-meter">${[1,2,3,4].map(i=>`<i class="${i<=Math.min(count,4)?'on':''}"></i>`).join('')}</div><small>${escapeHtml(msg)}</small></div>`);}); }
  function metaBadge(m){if(!m)return '';const due=m.update_due_at?new Date(m.update_due_at):null,late=due&&due.getTime()<Date.now(),label=m.confidence==='high'?t('high'):m.confidence==='trying'?t('trying'):t('medium');return `<span class="suite-meta-badge ${m.confidence} ${late?'suite-deadline-over':''}">${escapeHtml(label)}${due?` · ${escapeHtml(late?t('overdue'):t('due',{time:relativeTime(due)}))}`:''}</span>`;}
  function decorateClaims(){ $$('.job-card[data-job-id]').forEach(card=>{if(card.querySelector('.suite-claim-meta'))return;const j=state.jobs.find(x=>Number(x.id)===Number(card.dataset.jobId));if(!j||!isOperational(j))return;const active=claimRows(j).filter(claimActive);if(!active.length)return;const html=`<div class="suite-claim-meta" style="display:grid;gap:6px;margin:8px 0 2px;font-size:10px">${active.map(c=>`<div><strong>${escapeHtml(c.agent_name)}</strong>${metaBadge(metaFor(j.id,c.agent_name))}${isSameAgent(c.agent_name)?` <button class="suite-plan-button" type="button" data-suite-plan="${j.id}">${escapeHtml(t('plan'))}</button>`:''}</div>`).join('')}</div>`;(card.querySelector('.worker-capacity')||card.querySelector('.job-transparency'))?.insertAdjacentHTML('beforeend',html);}); }

  function historyJobs(){return state.jobs.filter(j=>isOperational(j)&&['filled','closed'].includes(j.status)).sort((a,b)=>new Date(b.filled_at||b.closed_at||b.updated_at)-new Date(a.filled_at||a.closed_at||a.updated_at));}
  function renderHistory(){const list=historyJobs(),filled=list.filter(j=>j.status==='filled'),closed=list.filter(j=>j.status==='closed'),found=filled.reduce((s,j)=>s+totals(j).found,0),needed=list.reduce((s,j)=>s+Math.max(1,Number(j.workers_needed)||1),0),rate=needed?Math.round(found/needed*100):0;historyDashboard.innerHTML=`<div class="suite-head"><div><h3>${escapeHtml(t('history_title'))}</h3><p>${escapeHtml(t('history_subtitle'))}</p></div></div><div class="suite-history-summary"><div><strong>${filled.length}</strong><small>${escapeHtml(t('h_filled'))}</small></div><div><strong>${closed.length}</strong><small>${escapeHtml(t('h_closed'))}</small></div><div><strong>${found}</strong><small>${escapeHtml(t('h_workers'))}</small></div><div><strong>${rate}%</strong><small>${escapeHtml(t('h_rate'))}</small></div></div>${list.length?`<div class="suite-history-list">${list.slice(0,100).map(j=>`<div class="suite-history-row"><strong>${escapeHtml(j.trade)}</strong><span>${escapeHtml(j.created_by||t('unknown'))}</span><span>${escapeHtml(String(j.status).toUpperCase())}</span><span>${escapeHtml(formatDate(j.filled_at||j.closed_at||j.updated_at,{day:'2-digit',month:'short',year:'numeric'}))}</span></div>`).join('')}</div>`:`<div class="recommend-empty">${escapeHtml(t('history_none'))}</div>`}`;}

  function notifications(){const seen=Number(localStorage.getItem(`rf_seen_${state.email||state.agent}`)||0),out=[];activeJobs().forEach(j=>{if(isSameAgent(j.created_by))claimRows(j).forEach(c=>{const ts=new Date(c.created_at).getTime();if(ts>seen&&ts>Date.now()-2*DAY)out.push({ts,text:t('notify_claim',{name:c.agent_name,trade:j.trade})});});const mine=claimRows(j).find(c=>isSameAgent(c.agent_name)&&claimActive(c));if(mine){const ju=new Date(j.updated_at||j.created_at).getTime(),cu=new Date(mine.updated_at||mine.created_at).getTime();if(ju>cu+60000&&ju>seen)out.push({ts:ju,text:t('notify_change',{trade:j.trade})});const m=metaFor(j.id,mine.agent_name);if(m?.update_due_at){const ts=new Date(m.update_due_at).getTime();if(ts<Date.now()&&ts>seen)out.push({ts,text:t('notify_due',{trade:j.trade})});}}});return out.sort((a,b)=>b.ts-a.ts);}
  function renderNotifications(){const n=notifications(),badge=$('#suiteNotifyCount');badge.textContent=n.length;badge.hidden=!n.length;$('#suiteNotificationList').innerHTML=n.length?n.map(x=>`<div class="suite-notification"><strong>${escapeHtml(x.text)}</strong><span>${escapeHtml(relativeTime(new Date(x.ts)))}</span></div>`).join(''):`<div class="suite-notification"><span>${escapeHtml(t('notify_none'))}</span></div>`;}

  function matchScore(w,j){let s=0,wt=normalizeName(w.trade),jt=normalizeName(j.trade);if(wt&&jt)s+=wt===jt?65:(wt.includes(jt)||jt.includes(wt)?48:0);const wp=String(w.postcode||'').replace(/\s/g,'').toUpperCase(),jp=String(j.postcode||'').replace(/\s/g,'').toUpperCase();if(wp&&jp)s+=wp===jp?25:(wp.slice(0,3)===jp.slice(0,3)?18:(wp.slice(0,2)===jp.slice(0,2)?10:0));const wl=normalizeName(w.location),jl=normalizeName(j.location);if(wl&&jl&&(wl.includes(jl)||jl.includes(wl)))s+=15;s+=Math.min(10,totals(j).free*2);if(j.priority==='urgent')s+=5;return Math.min(99,s);}
  function renderHotMatches(){const list=$('#hotWorkerList');if(!list)return;let panel=$('#suiteHotMatchPanel');if(!panel){panel=document.createElement('section');panel.id='suiteHotMatchPanel';panel.className='suite-hot-match-panel';list.after(panel);}const workers=hotWorkers();panel.innerHTML=workers.length?`<h4>${escapeHtml(t('hot_match'))}</h4><p style="margin:0;color:#7a8998;font-size:10px">${escapeHtml(t('hot_hint'))}</p>${workers.map(w=>{const d=parseHot(w),matches=activeJobs().filter(j=>totals(j).free>0).map(j=>({j,score:matchScore(w,j)})).filter(x=>x.score>=45).sort((a,b)=>b.score-a.score).slice(0,3);return `<div class="suite-hot-match-worker"><strong>🔥 ${escapeHtml(d.ref||'Worker')} · ${escapeHtml(w.trade)}</strong>${matches.length?matches.map(x=>`<div class="suite-match-row"><div><b>${escapeHtml(x.j.trade)}</b><span> · First: ${escapeHtml(x.j.created_by||t('unknown'))}</span></div><div class="suite-match-score">${x.score}%</div><button type="button" data-suite-assign-hot="${x.j.id}" data-hot-ref="${escapeHtml(d.ref||'Worker')}">${escapeHtml(t('assign'))}</button></div>`).join(''):`<div style="margin-top:7px;font-size:10px;color:#8b7a62">${escapeHtml(t('no_match'))}</div>`}</div>`;}).join('')}`:'';}

  function applySuiteView(){attentionDashboard.classList.add('transparency-hidden');historyDashboard.classList.add('transparency-hidden');$$('[data-suite-view]').forEach(b=>b.classList.toggle('is-active',b.dataset.suiteView===suite.view));if(!suite.view)return;['#jobsGrid','#firstDashboard','#secondDashboard','#recommendationDashboard'].forEach(s=>$(s)?.classList.add('transparency-hidden'));$('.toolbar')?.classList.add('transparency-hidden');(suite.view==='attention'?attentionDashboard:historyDashboard).classList.remove('transparency-hidden');const h=$('.section-heading h2');if(h)h.textContent=suite.view==='attention'?t('suite_attention'):t('suite_history');}
  function decorateAll(){renderCommand();renderAttention();renderActivity();renderHistory();decorateFirsts();decorateSeconds();decorateClaims();renderNotifications();if($('#hotWorkerDialog')?.open)renderHotMatches();applySuiteView();}

  render = function operationsRender(){baseRender();decorateAll();};
  applyLanguage = function operationsLanguage(){baseApplyLanguage();decorateAll();};

  function openJob(id){suite.view='';localStorage.removeItem(VIEW_KEY);switcher.querySelector('[data-board-view="jobs"]')?.click();setTimeout(()=>{const card=document.querySelector(`.job-card[data-job-id="${id}"]`);card?.scrollIntoView({behavior:'smooth',block:'center'});card?.classList.add('recommend-highlight');setTimeout(()=>card?.classList.remove('recommend-highlight'),1800);},100);}

  switcher.addEventListener('click',e=>{const b=e.target.closest('[data-suite-view]');if(b){suite.view=b.dataset.suiteView;localStorage.setItem(VIEW_KEY,suite.view);decorateAll();return;}if(e.target.closest('button')){suite.view='';localStorage.removeItem(VIEW_KEY);}},true);
  command.addEventListener('click',e=>{const b=e.target.closest('[data-suite-nav]');if(!b)return;const v=b.dataset.suiteNav;if(v==='attention'){suite.view='attention';localStorage.setItem(VIEW_KEY,'attention');decorateAll();}else if(v==='hot'){$('#hotWorkerButton')?.click();setTimeout(renderHotMatches,100);}else{suite.view='';localStorage.removeItem(VIEW_KEY);switcher.querySelector(v==='seconds'?'[data-ops-view="seconds"]':'[data-board-view="jobs"]')?.click();}});
  attentionDashboard.addEventListener('click',e=>{const b=e.target.closest('[data-suite-open-job]');if(b)openJob(Number(b.dataset.suiteOpenJob));});
  notifyButton.addEventListener('click',()=>{notifyPanel.hidden=!notifyPanel.hidden;if(!notifyPanel.hidden)renderNotifications();});
  $('#suiteMarkSeen').addEventListener('click',()=>{localStorage.setItem(`rf_seen_${state.email||state.agent}`,String(Date.now()));renderNotifications();});

  document.addEventListener('click',e=>{const p=e.target.closest('[data-suite-plan]');if(p){const id=Number(p.dataset.suitePlan),j=state.jobs.find(x=>Number(x.id)===id),c=j&&claimRows(j).find(x=>isSameAgent(x.agent_name)&&claimActive(x));if(!c)return;const m=metaFor(id,c.agent_name),val=m?.confidence||'medium';$('#suitePlanJobId').value=id;document.querySelector(`input[name="suiteConfidence"][value="${val}"]`)?.click();$('#suitePlanNote').value=m?.note||'';$('#suitePlanDue').value='2';$('#suitePlanDialog').showModal();return;}const a=e.target.closest('[data-suite-assign-hot]');if(a){const id=Number(a.dataset.suiteAssignHot),ref=a.dataset.hotRef||'Hot Worker';$('#hotWorkerDialog')?.close();openJob(id);setTimeout(()=>{const card=document.querySelector(`.job-card[data-job-id="${id}"]`),j=state.jobs.find(x=>Number(x.id)===id),mine=j&&claimRows(j).find(c=>isSameAgent(c.agent_name)&&claimActive(c)),btn=card?.querySelector(mine?'[data-action="found-slots"]':'[data-action="claim-slots"]');if(btn){btn.click();if(mine)setTimeout(()=>{if($('#foundNote'))$('#foundNote').value=`Hot Worker ${ref}`;},60);}},220);}});
  $('#suitePlanClose').addEventListener('click',()=>$('#suitePlanDialog').close());
  $('#suitePlanCancel').addEventListener('click',()=>$('#suitePlanDialog').close());
  $('#suitePlanForm').addEventListener('submit',async e=>{e.preventDefault();const id=Number($('#suitePlanJobId').value),confidence=document.querySelector('input[name="suiteConfidence"]:checked')?.value||'medium',v=$('#suitePlanDue').value;let due;if(v==='today'){due=new Date();due.setHours(18,0,0,0);if(due.getTime()<Date.now())due.setDate(due.getDate()+1);}else due=new Date(Date.now()+Number(v)*HOUR);try{setBusy(true,t('saving'));await opsFetch('set_claim_meta',{job_id:id,agent_name:state.agent,agent_email:state.email,confidence,update_due_at:due.toISOString(),note:$('#suitePlanNote').value.trim()});toast(t('plan_saved'),'success');$('#suitePlanDialog').close();await refreshOps();}catch(err){toast(err.message||t('network_error'),'error',5000);}finally{setBusy(false);}});

  $('#hotWorkerButton')?.addEventListener('click',()=>setTimeout(renderHotMatches,120));
  window.setInterval(()=>{if(!document.hidden){refreshOps();decorateAll();}},60000);
  applyLanguage();
  refreshOps();
  decorateAll();
})();
