const makeAgents = (prefix, count) =>
  Array.from({ length: count }, (_, index) => `${prefix}-${String(index + 1).padStart(2, '0')}`)

export const companySnapshot = {
  peopleModelled: 78,
  teams: 5,
  verifiedPhoneRecords: 71779,
  yellowDataset: 23000,
  jobPostings: 109,
  uniqueJobContacts: 50,
  sourcingSources: 15,
  confirmedCompanies: 25,
  trackedOffers: 22,
  floors: 10,
  publicMode: 'Aggregate & anonymised',
  snapshotLabel: 'Ultima situație operațională cunoscută',
}

export const teams = [
  {
    id: 'yellow', name: 'Yellow', count: 25, color: '#ffd21f', accent: '#fff2a8',
    purpose: 'Recrutare și apelare dintr-un pool dedicat de muncitori.',
    people: makeAgents('Y', 25),
  },
  {
    id: 'blue', name: 'Blue', count: 23, color: '#3b82f6', accent: '#b9d5ff',
    purpose: 'Recrutare, căutare strictă după meserie și urmărirea apelurilor.',
    people: makeAgents('B', 23),
  },
  {
    id: 'posting', name: 'Posting', count: 15, color: '#a855f7', accent: '#e7c8ff',
    purpose: 'Postări, comunități, sourcing și generare de leaduri.',
    people: makeAgents('P', 15),
  },
  {
    id: 'classic', name: 'Classic', count: 12, color: '#20c7aa', accent: '#c7f5ed',
    purpose: 'Fluxul clasic de recrutare și follow-up operațional.',
    people: makeAgents('C', 12),
  },
  {
    id: 'red', name: 'RED', count: 3, color: '#ff4d68', accent: '#ffc0ca',
    purpose: 'Căutare rapidă și listă concentrată de muncitori noi.',
    people: makeAgents('R', 3),
  },
]

export const roles = [
  { id: 'recruiter', name: 'Recruitment Caller', icon: '☎', outcome: 'Vorbește cu muncitori, confirmă disponibilitatea și creează următorul pas.', skills: ['comunicare', 'meserii construcții', 'follow-up'] },
  { id: 'sourcer', name: 'Internet Sourcer', icon: '⌕', outcome: 'Găsește leaduri noi în comunități, site-uri și anunțuri.', skills: ['research', 'deduplicare', 'sursă'] },
  { id: 'poster', name: 'Posting Agent', icon: '✦', outcome: 'Publică mesaje de recrutare și urmărește răspunsurile.', skills: ['copy', 'grupuri', 'campanii'] },
  { id: 'matcher', name: 'Job Matcher', icon: '↔', outcome: 'Potrivește omul potrivit cu jobul potrivit.', skills: ['trade', 'postcode', 'disponibilitate'] },
  { id: 'first', name: 'Company Caller / First', icon: '🏢', outcome: 'Contactează companii, identifică nevoi și recuperează oportunități.', skills: ['B2B', 'job intake', 'recovery'] },
  { id: 'data', name: 'Data Quality Operator', icon: '▦', outcome: 'Curăță, normalizează și reconciliază bazele de date.', skills: ['QA', 'matching', 'import'] },
  { id: 'callqa', name: 'Call QA & AI Reviewer', icon: '◉', outcome: 'Verifică recording, transcript, rezumat și follow-up.', skills: ['Dialpad', 'AI', 'coaching'] },
  { id: 'trainer', name: 'Education & Onboarding', icon: '⌁', outcome: 'Pregătește agenți noi și menține standardele de lucru.', skills: ['training', 'scripts', 'consimțământ'] },
  { id: 'coordinator', name: 'Coordinator', icon: '⌘', outcome: 'Distribuie oamenii și elimină blocajele dintre fluxuri.', skills: ['alocare', 'priorități', 'escaladare'] },
  { id: 'manager', name: 'Operations Manager', icon: '◆', outcome: 'Urmărește KPI, riscuri, productivitate și sisteme.', skills: ['management', 'raportare', 'control'] },
]

export const apps = [
  { id: 'blue', name: 'Blue', category: 'Recruitment', status: 'Active', description: 'Căutare și apelare de muncitori din pool dedicat.' },
  { id: 'yellow', name: 'Yellow', category: 'Recruitment', status: 'Active', description: 'Flux separat de recrutare și distribuire a leadurilor.' },
  { id: 'red', name: 'RED', category: 'Sourcing', status: 'Active', description: 'Muncitori noi și căutare rapidă.' },
  { id: 'iza', name: 'IZA', category: 'Recruitment', status: 'Specialised', description: 'Flux dedicat unei echipe / operațiuni separate.' },
  { id: 'jobboard', name: 'Job Board', category: 'Matching', status: 'Active', description: 'Joburi, claim, muncitor găsit și vizibilitate între agenți.' },
  { id: 'dialpad', name: 'Dialpad AI', category: 'Calls', status: 'Integrating', description: 'Recording, transcript, summary și follow-up.' },
  { id: 'reddashboard', name: 'RED Dashboard', category: 'Data', status: 'Active', description: 'Consolidare, filtre, surse și vizualizare muncitori.' },
  { id: 'masterregistry', name: 'Master Registry', category: 'Data', status: 'Continuous', description: 'Registru central, deduplicare și reconciliere.' },
  { id: 'firstcallers', name: 'First Callers', category: 'Companies', status: 'Designed', description: 'Companii, nevoi, recovery și job intake.' },
  { id: 'control', name: 'Company Control Center', category: 'Management', status: 'Active', description: 'Probleme, KPI, proiecte și escaladări.' },
  { id: 'dealfinder', name: 'Deal Finder', category: 'Opportunities', status: 'Exploring', description: 'Oportunități imobiliare și comerciale.' },
]

export const businessFloors = [
  {
    id: 'welcome', number: 1, icon: '◎', color: '#79d7ff',
    title: 'Welcome & Business Map', short: 'Welcome',
    subtitle: 'Ce face compania și cum circulă valoarea',
    description: 'RecruitFlow este un sistem operațional de recrutare: găsește muncitori, curăță datele, creează joburi, contactează companii, potrivește oameni cu oportunități și urmărește rezultatul.',
    metrics: [['78', 'oameni modelați'], ['10', 'niveluri business'], ['11', 'aplicații / sisteme'], ['5', 'echipe active']],
    workflow: ['Sursă nouă', 'Profil curățat', 'Job potrivit', 'Apel / claim', 'Rezultat & follow-up'],
    roles: ['Recruiter', 'Sourcer', 'Matcher', 'Manager'],
    apps: ['RecruitFlow HQ', 'Company Control Center'],
    people: 8, scene: 'reception',
    whatYouCanDo: ['Înțelegi compania în 3 minute', 'Alegi un rol', 'Urmărești traseul unui lead', 'Pornești turul ghidat'],
  },
  {
    id: 'teams', number: 2, icon: '♟', color: '#8fb5ff',
    title: 'Teams & Roles', short: 'Teams',
    subtitle: '78 de oameni, 5 echipe, 10 tipuri de rol',
    description: 'Aici vezi cum sunt împărțite echipele Yellow, Blue, Posting, Classic și RED. Etichetele publice sunt anonimizate, iar fiecare avatar reprezintă un loc real în structură.',
    metrics: [['25', 'Yellow'], ['23', 'Blue'], ['15', 'Posting'], ['12', 'Classic'], ['3', 'RED']],
    workflow: ['Alocare', 'Obiectiv zilnic', 'Activitate', 'Control calitate', 'Realocare'],
    roles: roles.map(role => role.name),
    apps: ['Blue', 'Yellow', 'RED', 'IZA'],
    people: 78, scene: 'teams',
    whatYouCanDo: ['Suni muncitori', 'Cauți leaduri', 'Postezi campanii', 'Coordonezi echipe'],
  },
  {
    id: 'calls', number: 3, icon: '☎', color: '#ff9f6e',
    title: 'Calls & AI Intelligence', short: 'Calls',
    subtitle: 'Apel → recording → transcript → rezumat → follow-up',
    description: 'Centrul de apeluri unifică activitatea agenților și pregătește analiza AI. Cifrele live rămân marcate ca neconectate până când sursa reală este disponibilă.',
    metrics: [['5', 'linii de aplicații'], ['3', 'etape AI'], ['7', 'tipuri evenimente'], ['0', 'cifre inventate']],
    workflow: ['Apel pornit', 'Recording primit', 'Transcript generat', 'Rezumat AI', 'Acțiune recomandată'],
    roles: ['Recruitment Caller', 'Call QA & AI Reviewer', 'Coordinator'],
    apps: ['Dialpad AI', 'Dashboard apeluri și performanță'],
    people: 15, scene: 'calls',
    whatYouCanDo: ['Suni', 'Verifici outcome', 'Citești rezumatul', 'Planifici follow-up'],
  },
  {
    id: 'apps', number: 4, icon: '▣', color: '#b98cff',
    title: 'Recruitment Apps Lab', short: 'Apps',
    subtitle: 'Blue, Yellow, RED, IZA și Job Board',
    description: 'Fiecare aplicație are un scop separat: pool de leaduri, reguli de căutare, claim pe job, colaborare între agenți și vizibilitate asupra activității.',
    metrics: [['4', 'aplicații recrutare'], ['1', 'Job Board comun'], ['2', 'limbi UI'], ['3', 'pool-uri planificate']],
    workflow: ['Alegi aplicația', 'Cauți meserie / zonă', 'Primești lead', 'Claim / apel', 'Actualizezi rezultatul'],
    roles: ['Recruiter', 'Job Matcher', 'Coordinator', 'Product QA'],
    apps: ['Blue', 'Yellow', 'RED', 'IZA', 'Job Board'],
    people: 12, scene: 'apps',
    whatYouCanDo: ['Cauți muncitori', 'Vezi cine lucrează același job', 'Marchezi găsit', 'Eviți dublarea apelurilor'],
  },
  {
    id: 'database', number: 5, icon: '▦', color: '#52e0ba',
    title: 'Worker Database & Data Quality', short: 'Database',
    subtitle: 'Date curate înainte de apel',
    description: 'Baza de date este motorul companiei. Leadurile sunt reconciliate, deduplicate și normalizate; regula publică de calitate păstrează primul postcode valid și prima meserie validă.',
    metrics: [['71,779', 'telefoane verificate'], ['23k', 'dataset Yellow'], ['1', 'postcode păstrat'], ['1', 'trade păstrat']],
    workflow: ['Import sursă', 'Normalizare telefon', 'Deduplicare', 'Postcode & trade', 'Status & disponibilitate'],
    roles: ['Data Quality Operator', 'Database Manager', 'Control Quality'],
    apps: ['Master Registry', 'RED Dashboard', 'Supabase'],
    people: 14, scene: 'database',
    whatYouCanDo: ['Cureți date', 'Identifici dubluri', 'Completezi câmpuri lipsă', 'Pregătești importuri'],
  },
  {
    id: 'jobs', number: 6, icon: '↔', color: '#ffd166',
    title: 'Jobs & Matching Engine', short: 'Jobs',
    subtitle: 'De la nevoie la muncitor potrivit',
    description: 'Joburile intră într-un board comun și sunt potrivite după meserie, postcode, disponibilitate, experiență și stare. Claim-ul face vizibil cine lucrează deja pe un job.',
    metrics: [['109', 'job postings'], ['50', 'contacte unice'], ['15', 'surse'], ['5', 'dimensiuni matching']],
    workflow: ['Job introdus', 'Date obligatorii', 'Matching automat', 'Agent claim', 'Muncitor găsit / filled'],
    roles: ['Job Matcher', 'Recruiter', 'Coordinator'],
    apps: ['Job Board', 'Active Workers', 'Worker Filters'],
    people: 12, scene: 'jobs',
    whatYouCanDo: ['Introduci job', 'Compari muncitori', 'Dai claim', 'Marchezi filled'],
  },
  {
    id: 'companies', number: 7, icon: '🏢', color: '#4cc9f0',
    title: 'First, Companies & Recovery', short: 'Companies',
    subtitle: 'Cerere B2B, job intake și recuperarea oportunităților',
    description: 'Echipa First contactează companii, identifică nevoi de personal, creează joburi și recuperează leaduri care nu au ajuns la rezultat.',
    metrics: [['25', 'companii confirmate'], ['22', 'oferte urmărite'], ['3', 'stadii recovery'], ['1', 'flux First']],
    workflow: ['Companie găsită', 'Primul apel', 'Nevoie confirmată', 'Job creat', 'Recovery / follow-up'],
    roles: ['Company Caller / First', 'Recovery Agent', 'Job Intake', 'Coordinator'],
    apps: ['First Callers', 'Company Workflow', 'Recovery'],
    people: 12, scene: 'companies',
    whatYouCanDo: ['Cauți companii', 'Suni decidenți', 'Înregistrezi nevoia', 'Recuperezi oportunități'],
  },
  {
    id: 'education', number: 8, icon: '⌁', color: '#f78fb3',
    title: 'Education, Onboarding & QA', short: 'Education',
    subtitle: 'Cum transformăm un agent nou într-un operator bun',
    description: 'Aici sunt explicate onboarding-ul, scripturile, consimțământul, meseriile din construcții, simulările de apel și bucla de feedback.',
    metrics: [['10', 'roluri prezentate'], ['3', 'faze onboarding'], ['2', 'bucle QA'], ['1', 'standard comun']],
    workflow: ['Orientare', 'Training aplicații', 'Simulare apel', 'Activitate supravegheată', 'Certificare internă'],
    roles: ['Education & Onboarding', 'Call QA', 'Team Lead', 'New Agent'],
    apps: ['Education Recruitment', 'Scripts Library', 'QA Dashboard'],
    people: 10, scene: 'education',
    whatYouCanDo: ['Înveți rolul', 'Exersezi apeluri', 'Primești feedback', 'Treci la producție'],
  },
  {
    id: 'sourcing', number: 9, icon: '⌕', color: '#ff7b54',
    title: 'Internet Sourcing & Growth', short: 'Sourcing',
    subtitle: 'Comunități, site-uri, postări și muncitori noi',
    description: 'Echipa de growth caută muncitori în comunități românești și internaționale, pe site-uri și în anunțuri, apoi trimite leadurile către registrul central.',
    metrics: [['15', 'surse urmărite'], ['10+', 'meserii'], ['6+', 'comunități'], ['1', 'registru consolidat']],
    workflow: ['Cuvinte-cheie', 'Sursă', 'Contact public', 'Deduplicare', 'Trimitere în RED / Master'],
    roles: ['Internet Sourcer', 'Posting Agent', 'Data Quality Operator'],
    apps: ['RED', 'RED Dashboard', 'Campaign Forms'],
    people: 16, scene: 'sourcing',
    whatYouCanDo: ['Cauți leaduri', 'Publici campanii', 'Etichetezi sursa', 'Măsori randamentul'],
  },
  {
    id: 'management', number: 10, icon: '◆', color: '#a7f3d0',
    title: 'Management, Control & Opportunities', short: 'Control',
    subtitle: 'KPI, riscuri, sisteme și direcții noi',
    description: 'Ultimul nivel reunește managementul operațional, controlul calității, starea sistemelor, proiectele companiei și explorarea de oportunități precum Deal Finder.',
    metrics: [['4', 'riscuri urmărite'], ['5+', 'dashboarduri'], ['3', 'clase sisteme'], ['100%', 'date publice mascate']],
    workflow: ['Semnal', 'Diagnostic', 'Prioritate', 'Owner', 'Remediere & verificare'],
    roles: ['Operations Manager', 'Coordinator', 'Control Quality', 'Systems Owner'],
    apps: ['Company Control Center', 'Deal Finder', 'System Health', 'Project Registry'],
    people: 10, scene: 'management',
    whatYouCanDo: ['Vezi compania dintr-o privire', 'Prioritizezi probleme', 'Verifici sisteme', 'Explorezi oportunități'],
  },
]

export const visitorMissions = [
  { id: 'tour', title: 'Turul turnului', description: 'Vizitează toate cele 10 niveluri.', target: 10, type: 'floors' },
  { id: 'data-rule', title: 'Regula datelor curate', description: 'Vizitează nivelul Database.', floorId: 'database', target: 1, type: 'floor' },
  { id: 'job-flow', title: 'Traseul unui job', description: 'Vizitează nivelul Jobs.', floorId: 'jobs', target: 1, type: 'floor' },
  { id: 'call-ai', title: 'Apelul analizat', description: 'Vizitează nivelul Calls & AI.', floorId: 'calls', target: 1, type: 'floor' },
  { id: 'career', title: 'Găsește un rol', description: 'Deschide harta rolurilor.', target: 1, type: 'career' },
]

export const glossary = [
  ['Lead', 'Persoană sau companie care poate deveni oportunitate.'],
  ['Trade', 'Meseria principală din construcții.'],
  ['Postcode', 'Zona folosită pentru matching geografic.'],
  ['Claim', 'Semnal că un agent lucrează deja un job.'],
  ['First', 'Fluxul orientat spre companii și cerere.'],
  ['Second', 'Fluxul orientat spre muncitori și ofertă.'],
  ['Recovery', 'Reluarea unei oportunități rămase fără rezultat.'],
  ['Curated', 'Înregistrare verificată și normalizată.'],
]
