import * as THREE from 'three'
import { OrbitControls } from 'three/addons/controls/OrbitControls.js'
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js'
import { secondiCategories, allPeople, roleGroups, callCenters, globalMetrics } from './data.js'

const $=s=>document.querySelector(s)
const canvas=$('#world')
const renderer=new THREE.WebGLRenderer({canvas,antialias:true})
renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight)
renderer.shadowMap.enabled=true;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping
const scene=new THREE.Scene();scene.background=new THREE.Color(0x07101a);scene.fog=new THREE.Fog(0x07101a,45,115)
const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture
const camera=new THREE.PerspectiveCamera(43,innerWidth/innerHeight,.1,240);camera.position.set(-34,18,23)
const controls=new OrbitControls(camera,canvas);controls.enableDamping=true;controls.minDistance=8;controls.maxDistance=72;controls.maxPolarAngle=Math.PI*.48;controls.target.set(-34,1,0)
scene.add(new THREE.HemisphereLight(0xdceaff,0x111722,2.2))
const sun=new THREE.DirectionalLight(0xffffff,3.8);sun.position.set(-8,34,18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);scene.add(sun)

const centers={teams:new THREE.Vector3(-34,0,0),roles:new THREE.Vector3(0,0,0),calls:new THREE.Vector3(34,0,0)}
const views={teams:[new THREE.Vector3(-34,18,23),new THREE.Vector3(-34,1,0)],roles:[new THREE.Vector3(0,18,23),new THREE.Vector3(0,1,0)],calls:[new THREE.Vector3(34,18,23),new THREE.Vector3(34,1,0)]}
const labels={teams:[],roles:[],calls:[]},clickable=[],records={teams:new Map(),roles:new Map(),calls:new Map()},buildingLights={}
let current='teams',targetCamera=null

function box(w,h,d,color,o={}){const m=new THREE.MeshStandardMaterial({color,roughness:o.r??.58,metalness:o.m??.1,transparent:o.t??false,opacity:o.o??1});if(o.e){m.emissive=new THREE.Color(o.e);m.emissiveIntensity=o.ei??.3}const x=new THREE.Mesh(new THREE.BoxGeometry(w,h,d),m);x.castShadow=o.cs??true;x.receiveShadow=o.rs??true;return x}
function round(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect?ctx.roundRect(x,y,w,h,r):(ctx.rect(x,y,w,h));ctx.closePath()}
function label(title,sub,color,small=false){const c=document.createElement('canvas');c.width=small?620:900;c.height=small?140:220;const x=c.getContext('2d');round(x,12,12,c.width-24,c.height-24,small?22:32);x.fillStyle='rgba(4,8,15,.86)';x.fill();x.strokeStyle=color;x.lineWidth=small?3:5;x.stroke();x.textAlign='center';x.textBaseline='middle';x.fillStyle='#fff';x.font=small?'700 42px Arial':'900 64px Arial';x.fillText(title,c.width/2,sub?c.height*.42:c.height*.5);if(sub){x.fillStyle=color;x.font=small?'700 27px Arial':'800 34px Arial';x.fillText(sub,c.width/2,c.height*.72)}const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false}));s.scale.set(small?1.02:3.3,small?.22:.82,1);return s}
function addLabel(s,b,always=false){labels[b].push({s,always});return s}
function showLabels(){Object.entries(labels).forEach(([b,a])=>a.forEach(v=>v.s.visible=v.always||b===current))}
function person(color,scale=.82){const g=new THREE.Group(),cloth=new THREE.MeshStandardMaterial({color,roughness:.6,emissive:new THREE.Color(color),emissiveIntensity:.08});const body=new THREE.Mesh(new THREE.CapsuleGeometry(.14*scale,.38*scale,4,8),cloth);body.position.y=.59*scale;g.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.15*scale,10,8),new THREE.MeshStandardMaterial({color:0xd3a17c,roughness:.9}));head.position.y=.98*scale;g.add(head);for(const x of[-.08,.08]){const leg=new THREE.Mesh(new THREE.CapsuleGeometry(.05*scale,.3*scale,3,6),new THREE.MeshStandardMaterial({color:0x202936,roughness:.75}));leg.position.set(x*scale,.22*scale,0);g.add(leg)}return g}
function station(p,b){const g=new THREE.Group(),desk=box(1.02,.07,.52,0xd9e1ec,{r:.75,m:.03});desk.position.y=.66;g.add(desk);for(const x of[-.41,.41]){const l=box(.05,.64,.05,0x66748a,{m:.35});l.position.set(x,.32,0);g.add(l)}const screen=box(.4,.25,.03,0x101722,{e:p.color,ei:.38});screen.position.set(0,.89,-.07);g.add(screen);const avatar=person(p.color);avatar.position.set(0,.05,.35);avatar.rotation.y=Math.PI;g.add(avatar);const n=addLabel(label(p.name,'',p.color,true),b);n.position.set(0,1.37,.33);g.add(n);return g}
function standing(p,b){const g=new THREE.Group(),avatar=person(p.color,.78);avatar.position.y=.08;g.add(avatar);const n=addLabel(label(p.name,'',p.color,true),b);n.scale.set(.84,.18,1);n.position.y=1.35;g.add(n);return g}

function campus(){const ground=box(108,.35,38,0x0e1826,{r:.92,cs:false});ground.position.y=-.3;scene.add(ground);const road=box(102,.03,5,0x17263b,{r:.96,cs:false});road.position.set(0,-.1,15.5);scene.add(road);for(let x=-48;x<=48;x+=6){const mark=box(2.5,.02,.1,0x6f88a8,{cs:false,e:0x314b70});mark.position.set(x,-.07,15.5);scene.add(mark)}}
function shell(id,title,sub,color){const g=new THREE.Group();g.position.copy(centers[id]);const base=box(27,.3,23,0x101c2b,{r:.7,m:.18});base.position.y=-.08;g.add(base);const floor=box(25.8,.08,21.8,0x1a2738,{r:.9});floor.position.y=.12;g.add(floor);const glass=new THREE.MeshPhysicalMaterial({color:0x9bcaff,roughness:.12,transmission:.35,transparent:true,opacity:.15,side:THREE.DoubleSide});const back=new THREE.Mesh(new THREE.BoxGeometry(25.8,5.7,.1),glass);back.position.set(0,2.85,-10.9);g.add(back);for(const x of[-12.9,12.9]){const side=new THREE.Mesh(new THREE.BoxGeometry(.1,5.7,21.8),glass);side.position.set(x,2.85,0);g.add(side)}for(const x of[-12.8,-6.4,0,6.4,12.8]){const beam=box(.12,.12,21.7,0x33475f,{m:.56});beam.position.set(x,5.7,0);g.add(beam)}const sign=addLabel(label(title,sub,color),id,true);sign.scale.set(4.4,1.08,1);sign.position.set(0,6.8,-8.8);g.add(sign);const light=new THREE.PointLight(color,4.5,22,2);light.position.set(0,5.2,0);g.add(light);buildingLights[id]=light;scene.add(g);return g}
function hit(parent,w,d,b,type,id){const h=new THREE.Mesh(new THREE.BoxGeometry(w,3.4,d),new THREE.MeshBasicMaterial({visible:false}));h.position.y=1.8;h.userData={building:b,type,id};parent.add(h);clickable.push(h)}

function teamsBuilding(){const b=shell('teams','TEAMS BUILDING','78 oameni • 5 echipe','#78a9ff');const aisle=box(2.4,.02,20.5,0x233a58,{r:.95,cs:false});aisle.position.y=.18;b.add(aisle);const layout={yellow:[-7.1,-4.5,5,1.42,1.5],blue:[6.3,-4.5,5,1.42,1.5],red:[-8.5,6.8,3,1.45,1.5],posts:[-2.1,5.4,5,1.42,1.5],classic:[7.5,5.3,4,1.45,1.5]};secondiCategories.forEach(t=>{const [x,z,cols,sx,sz]=layout[t.id],g=new THREE.Group();g.position.set(x,0,z);const rows=Math.ceil(t.count/cols),ac=Math.min(cols,t.count),w=Math.max(3.1,(ac-1)*sx+1.5),d=Math.max(2.4,(rows-1)*sz+1.7);const f=box(w,.025,d,t.accent,{t:true,o:.48,r:.95,cs:false});f.position.y=.2;f.userData={building:'teams',type:'team',id:t.id};g.add(f);clickable.push(f);const sign=addLabel(label(t.name.toUpperCase(),`${t.count} oameni`,t.color),'teams');sign.scale.set(2.25,.62,1);sign.position.set(0,3.05,-d/2+.2);g.add(sign);const tw=(ac-1)*sx,td=(rows-1)*sz;t.people.forEach((name,i)=>{const s=station({name,color:t.color},'teams');s.position.set((i%cols)*sx-tw/2,.23,Math.floor(i/cols)*sz-td/2);g.add(s)});const light=new THREE.PointLight(t.color,2.4,7,2);light.position.set(0,3.3,0);g.add(light);hit(g,w,d,'teams','team',t.id);b.add(g);records.teams.set(t.id,{data:t,obj:g,light,floor:f})})}

function rolesBuilding(){const b=shell('roles','ROLES BUILDING','First • Second • Ambele','#52d6ff');const second=roleGroups.find(r=>r.id==='second'),cols=13,sx=1.35,sz=1.45,rows=Math.ceil(second.people.length/cols),w=(cols-1)*sx+1.4,d=(rows-1)*sz+1.65,g=new THREE.Group();g.position.set(0,0,-2.3);const f=box(w,.025,d,0x214157,{t:true,o:.8,r:.94,cs:false});f.position.y=.2;f.userData={building:'roles',type:'role',id:'second'};g.add(f);clickable.push(f);const sign=addLabel(label('SECOND',`${second.people.length} oameni • provizoriu`,second.color),'roles');sign.position.set(0,3.05,-d/2+.2);g.add(sign);const tw=(cols-1)*sx,td=(rows-1)*sz;second.people.forEach((p,i)=>{const a=standing(p,'roles');a.position.set((i%cols)*sx-tw/2,.22,Math.floor(i/cols)*sz-td/2);g.add(a)});const light=new THREE.PointLight(second.color,3.4,11,2);light.position.set(0,4,0);g.add(light);hit(g,w,d,'roles','role','second');b.add(g);records.roles.set('second',{data:second,obj:g,light,floor:f});[['first',-7],['both',7]].forEach(([id,x])=>{const r=roleGroups.find(q=>q.id===id),z=new THREE.Group();z.position.set(x,0,7.3);const floor=box(6.1,.025,4.1,r.color,{t:true,o:.23,r:.94,cs:false});floor.position.y=.2;floor.userData={building:'roles',type:'role',id};z.add(floor);clickable.push(floor);const s=addLabel(label(r.name.toUpperCase(),'0 oameni • de completat',r.color),'roles');s.scale.set(2.7,.7,1);s.position.set(0,2.8,-1.1);z.add(s);for(const dx of[-1.7,0,1.7]){const desk=box(1.1,.07,.55,0x738096,{t:true,o:.38});desk.position.set(dx,.72,.45);z.add(desk)}const l=new THREE.PointLight(r.color,1.8,7,2);l.position.set(0,3,0);z.add(l);hit(z,6.1,4.1,'roles','role',id);b.add(z);records.roles.set(id,{data:r,obj:z,light:l,floor})});const note=addLabel(label('ÎNCADRARE PROVIZORIE','Completez exact după poze','#9adfff'),'roles');note.scale.set(3.1,.72,1);note.position.set(0,2.4,8.3);b.add(note)}

function callsBuilding(){const b=shell('calls','CALLS CENTER','5 aplicații • panouri pregătite','#ff8e5c'),pos=[[-8.1,-4.3],[0,-4.3],[8.1,-4.3],[-4.1,5],[4.1,5]];callCenters.forEach((c,i)=>{const g=new THREE.Group();g.position.set(pos[i][0],0,pos[i][1]);const f=box(6.4,.04,5.4,c.color,{t:true,o:.22,r:.9,cs:false});f.position.y=.2;f.userData={building:'calls',type:'call',id:c.id};g.add(f);clickable.push(f);const frame=box(5.2,2,.18,0x101823,{r:.22,m:.45});frame.position.set(0,2.75,-2.2);g.add(frame);const screen=box(4.8,1.62,.04,0x111827,{e:c.color,ei:.25});screen.position.set(0,2.75,-2.08);g.add(screen);const txt=addLabel(label(c.name.toUpperCase(),`${c.callsToday} apeluri azi • demo`,c.color),'calls');txt.scale.set(3.4,.9,1);txt.position.set(0,2.75,-1.93);g.add(txt);for(const x of[-1.45,0,1.45]){const desk=box(1.12,.08,.58,0x738196,{r:.7});desk.position.set(x,.72,.5);g.add(desk);const op=person(c.color,.76);op.position.set(x,.18,1.05);op.rotation.y=Math.PI;g.add(op)}const light=new THREE.PointLight(c.color,3.2,7,2);light.position.set(0,3.6,0);g.add(light);hit(g,6.4,5.4,'calls','call',c.id);b.add(g);records.calls.set(c.id,{data:c,obj:g,light,floor:f})});const hub=label('LIVE DATA HUB','Dialpad / API • urmează conectarea','#ffad88');addLabel(hub,'calls');hub.position.set(0,2.7,.3);b.add(hub)}

campus();teamsBuilding();rolesBuilding();callsBuilding();showLabels()

const ui={eyebrow:$('#sidebar-eyebrow'),title:$('#sidebar-title'),copy:$('#sidebar-copy'),section:$('#section-label'),kpis:$('#global-kpis'),list:$('#zone-list'),panel:$('#detail-panel'),de:$('#detail-eyebrow'),dt:$('#detail-title'),dd:$('#detail-description'),dk:$('#detail-kpis'),dn:$('#detail-note'),roster:$('#roster-panel'),back:$('#roster-backdrop'),content:$('#roster-content')}
const metric=m=>ui.kpis.innerHTML=m.map(([v,l])=>`<div class="kpi-card"><div class="kpi-value">${v}</div><div class="kpi-label">${l}</div></div>`).join('')
function buttons(items){ui.list.innerHTML=items.map(i=>`<button class="zone-button" data-zone="${i.id}"><span class="zone-color" style="background:${i.color};box-shadow:0 0 18px ${i.color}88"></span><span class="zone-copy"><span class="zone-name">${i.name}</span><span class="zone-meta">${i.meta}</span></span><span class="zone-count" style="color:${i.color}">${i.count}</span></button>`).join('');ui.list.querySelectorAll('[data-zone]').forEach(b=>b.onclick=()=>select(current,b.dataset.zone,true))}
function sidebar(b){if(b==='teams'){ui.eyebrow.textContent='TEAMS BUILDING';ui.title.textContent='Open Office';ui.copy.textContent='Toți cei 78 de agenți sunt vizibili la birouri, grupați pe aplicație.';ui.section.textContent='Echipe';metric(globalMetrics);buttons(secondiCategories.map(x=>({id:x.id,name:x.name,color:x.color,meta:x.action,count:x.count})))}else if(b==='roles'){ui.eyebrow.textContent='ROLES BUILDING';ui.title.textContent='First / Second / Ambele';ui.copy.textContent='Încadrare provizorie. Toți cei 78 sunt momentan în Second până completăm după poze.';ui.section.textContent='Roluri';metric([['0','First'],['78','Second'],['0','Ambele'],['78','Total']]);buttons(roleGroups.map(x=>({id:x.id,name:x.name,color:x.color,meta:x.status,count:x.people.length})))}else{ui.eyebrow.textContent='CALLS CENTER';ui.title.textContent='Live Call Control';ui.copy.textContent='Panouri separate pentru fiecare aplicație. Valorile sunt 0 până conectăm sursa reală.';ui.section.textContent='Aplicații';metric([['5','Aplicații'],['0','Apeluri azi'],['0','Surse live'],['Demo','Status']]);buttons(callCenters.map(x=>({id:x.id,name:x.name,color:x.color,meta:x.status,count:x.callsToday})))}}
function reset(){records.teams.forEach(r=>{r.light.intensity=2.4;r.floor.material.opacity=.48});records.roles.forEach(r=>{r.light.intensity=r.data.id==='second'?3.4:1.8;r.floor.material.opacity=r.data.id==='second'?.8:.23});records.calls.forEach(r=>{r.light.intensity=3.2;r.floor.material.opacity=.22})}
function focus(obj,offset){const p=new THREE.Vector3();obj.getWorldPosition(p);targetCamera=[p.clone().add(offset),p.clone().add(new THREE.Vector3(0,1,0))]}
function select(b,id,move){reset();ui.list.querySelectorAll('[data-zone]').forEach(x=>x.classList.toggle('active',x.dataset.zone===id));const r=records[b].get(id);if(!r)return;r.light.intensity=8;r.floor.material.opacity=.9;if(b==='teams'){const t=r.data;ui.de.textContent=`${t.priority.toUpperCase()} • ${t.action.toUpperCase()}`;ui.dt.textContent=t.name;ui.dd.textContent=t.description;ui.dk.innerHTML=`<div class="detail-kpi"><strong>${t.count}</strong><span>oameni</span></div><div class="detail-kpi"><strong>${Math.round(t.count/78*100)}%</strong><span>din total</span></div><div class="detail-kpi"><strong>Activ</strong><span>status</span></div>`;ui.dn.innerHTML=`<strong>Nume:</strong> ${t.people.join(', ')}`;if(move)focus(r.obj,new THREE.Vector3(6.5,7.2,7.5))}else if(b==='roles'){const q=r.data;ui.de.textContent=`ROLES • ${q.status.toUpperCase()}`;ui.dt.textContent=q.name;ui.dd.textContent=q.description;ui.dk.innerHTML=`<div class="detail-kpi"><strong>${q.people.length}</strong><span>oameni</span></div><div class="detail-kpi"><strong>${q.status}</strong><span>încadrare</span></div><div class="detail-kpi"><strong>${q.people.length}</strong><span>vizibili 3D</span></div>`;ui.dn.innerHTML=q.people.length?`<strong>Nume:</strong> ${q.people.map(p=>p.name).join(', ')}`:'<strong>Pregătit:</strong> zona va fi completată după poze.';if(move)focus(r.obj,new THREE.Vector3(7,8,9))}else{const c=r.data;ui.de.textContent=`CALLS CENTER • ${c.name.toUpperCase()}`;ui.dt.textContent=`${c.name} Calls`;ui.dd.textContent='Panou pregătit pentru conectarea la datele reale de apeluri.';ui.dk.innerHTML=`<div class="detail-kpi"><strong>0</strong><span>apeluri azi</span></div><div class="detail-kpi"><strong>${c.agents}</strong><span>agenți</span></div><div class="detail-kpi"><strong>Offline</strong><span>sursă live</span></div>`;ui.dn.innerHTML=`<strong>Status:</strong> ${c.status}. Nu inventăm cifre până conectăm sursa reală.`;if(move)focus(r.obj,new THREE.Vector3(5.8,5.8,7.2))}ui.panel.classList.add('open')}
function setBuilding(b,move=true){current=b;ui.panel.classList.remove('open');document.querySelectorAll('[data-building]').forEach(x=>x.classList.toggle('active',x.dataset.building===b));showLabels();sidebar(b);if(move)targetCamera=[views[b][0].clone(),views[b][1].clone()]}

document.querySelectorAll('[data-building]').forEach(b=>b.onclick=()=>setBuilding(b.dataset.building))
$('#reset-view').onclick=()=>setBuilding(current);$('#close-detail').onclick=()=>{ui.panel.classList.remove('open');reset()}
ui.content.innerHTML=secondiCategories.map(t=>`<section class="roster-team"><div class="roster-team-head" style="border-left:5px solid ${t.color}"><span>${t.name}</span><span class="roster-team-count">${t.count} oameni</span></div><div class="roster-names">${t.people.map((n,i)=>`<div class="roster-person"><span style="background:${t.color}">${i+1}</span>${n}</div>`).join('')}</div></section>`).join('')
function roster(open){ui.roster.classList.toggle('open',open);ui.back.classList.toggle('open',open)}
$('#open-roster').onclick=()=>roster(true);$('#close-roster').onclick=()=>roster(false);ui.back.onclick=()=>roster(false)
const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();canvas.addEventListener('pointerdown',e=>{const r=canvas.getBoundingClientRect();pointer.x=(e.clientX-r.left)/r.width*2-1;pointer.y=-(e.clientY-r.top)/r.height*2+1;ray.setFromCamera(pointer,camera);const h=ray.intersectObjects(clickable,true)[0];if(h){const d=h.object.userData;if(d.building!==current)setBuilding(d.building,false);select(d.building,d.id,true)}})
addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight)})
sidebar('teams');const clock=new THREE.Clock();function animate(){requestAnimationFrame(animate);const t=clock.getElapsedTime();Object.entries(buildingLights).forEach(([b,l])=>l.intensity=b===current?5.2+Math.sin(t*1.2)*.5:2.1);if(targetCamera){camera.position.lerp(targetCamera[0],.075);controls.target.lerp(targetCamera[1],.075);if(camera.position.distanceTo(targetCamera[0])<.04)targetCamera=null}controls.update();renderer.render(scene,camera)}animate()
