import * as THREE from 'three'
import { OrbitControls } from 'three/addons/controls/OrbitControls.js'
import { secondiCategories, totalSecondi, globalMetrics } from './data.js'
const canvas=document.querySelector('#world'),renderer=new THREE.WebGLRenderer({canvas,antialias:false,alpha:false,powerPreference:'high-performance',precision:'mediump'}),mobile=matchMedia('(max-width:900px)').matches
renderer.setPixelRatio(Math.min(devicePixelRatio,mobile?.82:1));renderer.setSize(innerWidth,innerHeight);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=false
const scene=new THREE.Scene();scene.background=new THREE.Color(0xf0f4f8);scene.fog=new THREE.Fog(0xf0f4f8,44,88)
const camera=new THREE.PerspectiveCamera(48,innerWidth/innerHeight,.1,160);camera.position.set(0,25,37)
const controls=new OrbitControls(camera,renderer.domElement);Object.assign(controls,{enableDamping:true,dampingFactor:.16,rotateSpeed:.72,zoomSpeed:.9,panSpeed:.65,screenSpacePanning:true,minDistance:10,maxDistance:58,maxPolarAngle:Math.PI*.455});controls.target.set(0,1,0)
scene.add(new THREE.HemisphereLight(0xffffff,0x8b9aad,2.8));const sun=new THREE.DirectionalLight(0xffffff,1.9);sun.position.set(12,25,10);scene.add(sun)
const mats=new Map();function material(key,color,o={}){if(mats.has(key))return mats.get(key);const m=new THREE.MeshStandardMaterial({color,roughness:o.roughness??.72,metalness:o.metalness??.02,transparent:o.transparent??false,opacity:o.opacity??1});mats.set(key,m);return m}function box(w,h,d,color,o={}){return new THREE.Mesh(new THREE.BoxGeometry(w,h,d),new THREE.MeshStandardMaterial({color,roughness:o.roughness??.75,metalness:o.metalness??.02,transparent:o.transparent??false,opacity:o.opacity??1}))}
const tex=new Map();function label(text,color,small=true){const key=`${small?'s':'l'}:${text}:${color}`;let t=tex.get(key);if(!t){const c=document.createElement('canvas');c.width=small?256:512;c.height=small?48:120;const x=c.getContext('2d');x.fillStyle=small?'rgba(255,255,255,.91)':'rgba(8,13,22,.90)';x.fillRect(0,0,c.width,c.height);x.strokeStyle=small?'rgba(20,30,45,.12)':color;x.lineWidth=small?1:3;x.strokeRect(1,1,c.width-2,c.height-2);x.textAlign='center';x.textBaseline='middle';x.fillStyle=small?'#152235':'#fff';x.font=small?'700 16px Arial':'900 36px Arial';x.fillText(text,c.width/2,c.height/2);t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;t.minFilter=THREE.LinearFilter;tex.set(key,t)}const s=new THREE.Sprite(new THREE.SpriteMaterial({map:t,transparent:true,depthTest:false}));s.scale.set(small?.68:2.65,small?.105:.62,1);return s}
const floor=box(35,.1,30,0xf7f8fb,{roughness:.98});floor.position.y=-.05;scene.add(floor);const aisle=box(4,.012,29,0xd2dae5,{roughness:1});aisle.position.y=.007;scene.add(aisle);const back=box(35,5.8,.12,0xe7edf4,{roughness:.95});back.position.set(0,2.9,-15);scene.add(back)
const bodyGeo=new THREE.CapsuleGeometry(.18,.46,2,5),headGeo=new THREE.SphereGeometry(.18,6,5),deskGeo=new THREE.BoxGeometry(1.35,.08,.72),monitorGeo=new THREE.BoxGeometry(.54,.34,.035),chairGeo=new THREE.BoxGeometry(.36,.42,.36),deskMat=material('desk',0xf7f8fa,{roughness:.86}),chairMat=material('chair',0x536983,{roughness:.8}),skinMat=material('skin',0xd3a17d,{roughness:.92}),hairMat=material('hair',0x35251e,{roughness:.96})
function station(c,name){const g=new THREE.Group(),top=new THREE.Mesh(deskGeo,deskMat);top.position.y=.76;g.add(top);const mm=material(`mon:${c.id}`,0x182333,{roughness:.25});mm.emissive=new THREE.Color(c.color);mm.emissiveIntensity=.18;const mon=new THREE.Mesh(monitorGeo,mm);mon.position.set(0,1.03,-.2);g.add(mon);const chair=new THREE.Mesh(chairGeo,chairMat);chair.position.set(0,.48,.5);g.add(chair);const torso=new THREE.Mesh(bodyGeo,material(`body:${c.id}`,c.color,{roughness:.75}));torso.position.set(0,.58,.35);g.add(torso);const head=new THREE.Mesh(headGeo,skinMat);head.position.set(0,1.02,.35);g.add(head);const hair=new THREE.Mesh(headGeo,hairMat);hair.scale.set(1,.48,1);hair.position.set(0,1.09,.35);g.add(hair);const tag=label(name,c.color,true);tag.position.set(0,1.33,.38);g.add(tag);return g}
const layout={yellow:{x:-9,z:-7.2,cols:5,face:-Math.PI/2},blue:{x:9,z:-7.2,cols:5,face:Math.PI/2},posts:{x:-9,z:5.2,cols:5,face:-Math.PI/2},classic:{x:9,z:5.2,cols:4,face:Math.PI/2},red:{x:0,z:-12.1,cols:3,face:0}}
const clickable=[],sections=new Map(),raycaster=new THREE.Raycaster(),pointer=new THREE.Vector2();let flight=null,dirty=true,last=0
function addDepartment(c){const l=layout[c.id];if(!l)return;const rows=Math.ceil(c.people.length/l.cols),sx=2.02,sz=1.92,g=new THREE.Group();g.position.set(l.x,0,l.z);const width=Math.max(3,(Math.min(l.cols,c.people.length)-1)*sx+2.15),depth=Math.max(2.5,(rows-1)*sz+2.4),zone=box(width,.015,depth,c.accent,{transparent:true,opacity:.3,roughness:1});zone.position.y=.009;g.add(zone);const sign=label(`${c.name.toUpperCase()} • ${c.count}`,c.color,false);sign.position.set(0,3.35,-depth/2+.12);g.add(sign);const cols=Math.min(l.cols,c.people.length),tw=(cols-1)*sx,td=(rows-1)*sz;c.people.forEach((name,i)=>{const st=station(c,name);st.position.set((i%l.cols)*sx-tw/2,0,Math.floor(i/l.cols)*sz-td/2);st.rotation.y=l.face;g.add(st)});const hit=new THREE.Mesh(new THREE.BoxGeometry(width,3,depth),new THREE.MeshBasicMaterial({visible:false}));hit.position.y=1.5;hit.userData.categoryId=c.id;g.add(hit);clickable.push(hit);scene.add(g);sections.set(c.id,{category:c,group:g,layout:l})}secondiCategories.forEach(addDepartment)
function populateUI(){const k=document.querySelector('#global-kpis');if(k)k.innerHTML=globalMetrics.map(([v,l])=>`<div class="kpi-card"><div class="kpi-value">${v}</div><div class="kpi-label">${l}</div></div>`).join('');const list=document.querySelector('#zone-list');if(!list)return;list.innerHTML=secondiCategories.map(c=>`<button class="zone-button" data-zone="${c.id}"><span class="zone-color" style="background:${c.color}"></span><span class="zone-copy"><span class="zone-name">${c.name}</span><span class="zone-meta">${c.action}</span></span><span class="zone-count" style="color:${c.color}">${c.count}</span></button>`).join('');document.querySelectorAll('[data-zone]').forEach(b=>b.addEventListener('click',()=>focus(b.dataset.zone)))}
function flyTo(position,target,duration=500){flight={start:performance.now(),duration,fromP:camera.position.clone(),fromT:controls.target.clone(),toP:position,toT:target};dirty=true}function focus(id){const s=sections.get(id);if(!s)return;const c=s.category;document.querySelectorAll('.zone-button').forEach(b=>b.classList.toggle('active',b.dataset.zone===id));const title=document.querySelector('#detail-title');if(title)title.textContent=c.name;const desc=document.querySelector('#detail-description');if(desc)desc.textContent=c.description;const note=document.querySelector('#detail-note');if(note)note.innerHTML=`<strong>Nume:</strong> ${c.people.join(', ')}`;const p=new THREE.Vector3();s.group.getWorldPosition(p),off=s.layout.x<0?new THREE.Vector3(-6,5.7,3):s.layout.x>0?new THREE.Vector3(6,5.7,3):new THREE.Vector3(0,5.8,-5.5);flyTo(p.clone().add(off),p.clone().add(new THREE.Vector3(0,1,0)),450)}function reset(){flyTo(new THREE.Vector3(0,25,37),new THREE.Vector3(0,1,0),550)}
populateUI();reset();document.querySelector('#reset-view')?.addEventListener('click',reset);renderer.domElement.addEventListener('pointerup',ev=>{const r=renderer.domElement.getBoundingClientRect();pointer.x=((ev.clientX-r.left)/r.width)*2-1;pointer.y=-((ev.clientY-r.top)/r.height)*2+1;raycaster.setFromCamera(pointer,camera);const h=raycaster.intersectObjects(clickable,false)[0];if(h?.object.userData.categoryId)focus(h.object.userData.categoryId)});controls.addEventListener('start',()=>flight=null);controls.addEventListener('change',()=>dirty=true);window.addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setPixelRatio(Math.min(devicePixelRatio,matchMedia('(max-width:900px)').matches?.82:1));renderer.setSize(innerWidth,innerHeight);dirty=true});function ease(t){return 1-Math.pow(1-t,4)}function frame(now){requestAnimationFrame(frame);let moving=false;if(flight){const t=Math.min(1,(now-flight.start)/flight.duration),e=ease(t);camera.position.lerpVectors(flight.fromP,flight.toP,e);controls.target.lerpVectors(flight.fromT,flight.toT,e);moving=true;if(t>=1)flight=null}controls.update();if((dirty||moving)&&now-last>16){renderer.render(scene,camera);dirty=false;last=now}}requestAnimationFrame(frame)