const realCases = [
  {id:1,day:'20 AUG',status:'strong',worker:'M. V.',workerTrade:'Electrician',jobTrade:'Electrician',workerPostcode:'RG21…',second:'A. Gabi',callTime:'20 Aug · 08:21 UK',callOutcome:'Follow-up',job:'Electrician — RG2',jobPostcode:'RG2 7JG',rate:'£29/h',first:'Gabi',claimedJob:'Electrician — RG2 · £29/h',claimState:'claimed_later',claimLabel:'CLAIMED LATER',claimNote:'The RG2 job was claimed later, so it was not yet claimed at call time.',summary:'Worker was contacted about an electrician role in Reading for at least 3 months. He asked for the exact location and duration and said he would call back later.',why:['Exact trade','RG-area fit','3-month duration aligns'],confidence:99},
  {id:2,day:'20 AUG',status:'strong',worker:'V. P.',workerTrade:'Dryliner',jobTrade:'Dryliner',workerPostcode:'NW9…',second:'Miruna',callTime:'20 Aug · 10:14 UK',callOutcome:'Interested',job:'Dryliner — NW3',jobPostcode:'NW3 2AQ',rate:'£26/h',first:'A. Mario',claimedJob:null,claimState:'none',claimLabel:'NO CLAIM LINKED',claimNote:'No safe claim-to-call link found.',summary:'Candidate showed interest in dryliner work, asked for offers and agreed to continue on WhatsApp.',why:['Exact trade','Interested','Close London move'],confidence:98},
  {id:3,day:'20 AUG',status:'strong',worker:'M. F.',workerTrade:'Dryliner',jobTrade:'Dryliner',workerPostcode:'E15…',second:'M. Alessandro',callTime:'20 Aug · 08:52 UK',callOutcome:'Interested',job:'Dryliner — EC4M',jobPostcode:'EC4M',rate:'£220/day · £27.50/h',first:'G. Ionescu',claimedJob:null,claimState:'none',claimLabel:'NO CLAIM LINKED',claimNote:'No safe claim-to-call link found.',summary:'Worker was interested in a central-London dryliner role paying £220/day for 8 hours, available from next week and able to bring a friend.',why:['Exact trade','Exact £220/day discussed','Central London'],confidence:98},
  {id:4,day:'20 AUG',status:'strong',worker:'G. D. A. M.',workerTrade:'Scaffolder / Labourer',jobTrade:'Labourer',workerPostcode:'CR4…',second:'Styleoutlet',callTime:'20 Aug · 10:19 UK',callOutcome:'Follow-up',job:'Labourer — Croydon',jobPostcode:'CR2 0NL',rate:'£14.50/h',first:'R. Ionut',claimedJob:null,claimState:'none',claimLabel:'NO CLAIM LINKED',claimNote:'No safe claim-to-call link found.',summary:'Candidate was contacted about labourer work in Croydon, asked about the rate and agreed to receive the full offer on WhatsApp.',why:['Labourer-family trade','Croydon local','Rate requested'],confidence:96},
  {id:5,day:'20 AUG',status:'strong',worker:'E. B.',workerTrade:'Dryliner',jobTrade:'Dryliner',workerPostcode:'NW10…',second:'A. Mircea',callTime:'20 Aug · 09:49 UK',callOutcome:'Follow-up',job:'Dryliner — NW3',jobPostcode:'NW3 2AQ',rate:'£26/h',first:'A. Mario',claimedJob:null,claimState:'none',claimLabel:'NO CLAIM LINKED',claimNote:'No safe claim-to-call link found.',summary:'Conversation concerned dryliner and tape-and-jointer work; candidate asked whether there is work available now.',why:['Exact trade','NW10 → NW3','Asked for available work'],confidence:94},
  {id:6,day:'20 AUG',status:'strong',worker:'A. V.',workerTrade:'Shuttering Carpenter',jobTrade:'Shuttering Carpenter',workerPostcode:'ME15…',second:'Nicoleta',callTime:'20 Aug · 10:50 UK',callOutcome:'Follow-up',job:'Shuttering Carpenter — ME10',jobPostcode:'ME10 3LF',rate:'£26–27/h',first:'A. Cristescu',claimedJob:null,claimState:'none',claimLabel:'NO CLAIM LINKED',claimNote:'No safe claim-to-call link found.',summary:'Candidate is working through Saturday but may be available next week. A follow-up was agreed.',why:['Exact trade','Very close Kent move','Availability next week'],confidence:92},
  {id:7,day:'20 AUG',status:'followup',worker:'R. G.',workerTrade:'Labourer',jobTrade:'Labourer',workerPostcode:'BN11…',second:'Y. Arhannt',callTime:'20 Aug · 10:40 UK',callOutcome:'Follow-up',job:'Labourer — BN11',jobPostcode:'BN11',rate:'£15.50/h',first:'Dennis',claimedJob:'Labourer — BN11 · £15.50/h',claimState:'at_call',claimLabel:'CLAIMED BEFORE CALL',claimNote:'The Second claimed this BN11 job roughly 26 seconds before the call.',summary:'Candidate confirmed tomorrow is suitable for a visit or meeting and said he would be at home.',why:['Exact postcode family','Exact labourer profile','Claim existed before call'],confidence:94},
  {id:8,day:'20 AUG',status:'followup',worker:'N. K.',workerTrade:'Handyman',jobTrade:'Handyman',workerPostcode:'AL3…',second:'F. Parker',callTime:'20 Aug · 10:55 UK',callOutcome:'Follow-up',job:'Handyman — AL5',jobPostcode:'AL5 2FH',rate:'£21/h',first:'A. Mario',claimedJob:null,claimState:'none',claimLabel:'NO CLAIM LINKED',claimNote:'No safe claim-to-call link found.',summary:'Candidate was contacted about handyman work but was busy and could not discuss at that moment.',why:['Exact trade','AL3 → AL5','Needs callback'],confidence:84},
  {id:9,day:'20 AUG',status:'followup',worker:'M. R.',workerTrade:'Electrician',jobTrade:'Electrician',workerPostcode:'CV10…',second:'Adam M',callTime:'20 Aug · 10:33 UK',callOutcome:'Follow-up',job:'Electrician — RG2',jobPostcode:'RG2 7JG',rate:'£29/h',first:'Gabi',claimedJob:null,claimState:'none',claimLabel:'NO CLAIM LINKED',claimNote:'No safe claim-to-call link found.',summary:'Candidate was contacted about work around CB7 and asked to be called back in one minute.',why:['Exact trade','Real follow-up','Location needs confirmation'],confidence:68},
  {id:10,day:'20 AUG',status:'followup',worker:'V. P.',workerTrade:'Dryliner',jobTrade:'Dryliner',workerPostcode:'NW9…',second:'Miruna',callTime:'20 Aug · 10:14 UK',callOutcome:'Interested',job:'Dryliner — EN5',jobPostcode:'EN5',rate:'£27/h',first:'N. Robert',claimedJob:null,claimState:'none',claimLabel:'NO CLAIM LINKED',claimNote:'Alternative job; no exact claim link.',summary:'Candidate asked for dryliner offers and agreed to continue on WhatsApp.',why:['Alternative','Exact trade','North-London option'],confidence:87},

  {id:11,day:'19 AUG',status:'strong',worker:'C. D. L.',workerTrade:'Painter & Decorator',jobTrade:'Painter & Decorator',workerPostcode:'NW…',second:'P. Jones',callTime:'19 Aug · 19:49 UK',callOutcome:'Follow-up',job:'Painter — NW1',jobPostcode:'NW1 8XY',rate:'£22/h',first:'Alexandra',claimedJob:null,claimState:'none',claimLabel:'NO CLAIM LINKED',claimNote:'No safe claim-to-call link found for the 19 Aug call.',summary:'Worker discussed a long-term painter role around Islington/North-West London at £22/h, showed interest and asked for details on WhatsApp.',why:['Exact painter trade','NW London fit','£22/h aligns'],confidence:97},
  {id:12,day:'19 AUG',status:'strong',worker:'I. R.',workerTrade:'Plasterer / Renderer',jobTrade:'Renderer',workerPostcode:'SE14…',second:'S. Baer',callTime:'19 Aug · 18:30 UK',callOutcome:'Interested',job:'Renderer — SE28',jobPostcode:'SE28',rate:'£25/h',first:'N. Robert',claimedJob:null,claimState:'none',claimLabel:'NO CLAIM LINKED',claimNote:'No safe claim-to-call link found for the 19 Aug call.',summary:'Worker discussed long-term rendering in SE28, has 25 years experience, wants to start Monday and can bring two more renderers plus a labourer.',why:['Exact rendering context','SE14 → SE28','Interested + team'],confidence:97},
  {id:13,day:'19 AUG',status:'strong',worker:'I. M. V.',workerTrade:'Dryliner',jobTrade:'Dryliner',workerPostcode:'RG2…',second:'Thomas N',callTime:'19 Aug · 10:04 UK',callOutcome:'Follow-up',job:'Dryliner — RG2',jobPostcode:'RG2',rate:'£27/h',first:'N. Robert',claimedJob:null,claimState:'none',claimLabel:'NO CLAIM LINKED',claimNote:'No safe claim-to-call link found for the 19 Aug call.',summary:'Worker discussed a long-term RG2 dryliner role at £27/h. He was working at the time but agreed to keep contact and send documents.',why:['Exact trade','Exact RG2','Exact £27/h'],confidence:96},
  {id:14,day:'19 AUG',status:'strong',worker:'T. T.',workerTrade:'Roofing Labourer',jobTrade:'Labourer',workerPostcode:'N22…',second:'P. Cristian',callTime:'19 Aug · 15:03 UK',callOutcome:'Interested',job:'Labourer — N22',jobPostcode:'N22 5JY',rate:'£16/h',first:'A. Luca',claimedJob:null,claimState:'none',claimLabel:'NO CLAIM LINKED',claimNote:'No safe claim-to-call link found for the 19 Aug call.',summary:'Worker was offered labourer work in N22 at £16/h, showed interest, confirmed CSCS and agreed to continue on WhatsApp.',why:['N22 local','Interested','CSCS confirmed'],confidence:96},
  {id:15,day:'19 AUG',status:'strong',worker:'R. C.',workerTrade:'Electrician Improver',jobTrade:'Electrician',workerPostcode:'RG22…',second:'F. Parker',callTime:'19 Aug · 09:28 UK',callOutcome:'Follow-up',job:'Electrician — RG2',jobPostcode:'RG2',rate:'£29/h',first:'Gabi',claimedJob:null,claimState:'none',claimLabel:'NO CLAIM LINKED',claimNote:'No safe claim-to-call link found for the 19 Aug call.',summary:'Worker was contacted about an electrician role in the RG area, requested the details by email and agreed to continue on WhatsApp.',why:['Electrician-family trade','RG area','Requested details'],confidence:89},
  {id:16,day:'19 AUG',status:'followup',worker:'C.',workerTrade:'Shuttering Carpenter',jobTrade:'Shuttering Carpenter',workerPostcode:'E11…',second:'S. Baer',callTime:'19 Aug · 19:08 UK',callOutcome:'Follow-up',job:'Shuttering Carpenter — N6',jobPostcode:'N6',rate:'£27.50/h',first:'Gabi',claimedJob:null,claimState:'none',claimLabel:'NO CLAIM LINKED',claimNote:'No safe claim-to-call link found for the 19 Aug call.',summary:'Worker corrected the recruiter that he only works as a shuttering carpenter and agreed to receive suitable carpenter jobs on WhatsApp.',why:['Exact corrected trade','London job','Needs availability check'],confidence:89},
  {id:17,day:'19 AUG',status:'followup',worker:'S. M.',workerTrade:'Dryliner',jobTrade:'Dryliner',workerPostcode:'E17…',second:'S. Baer',callTime:'19 Aug · 19:37 UK',callOutcome:'Follow-up',job:'Dryliner — E1W',jobPostcode:'E1W',rate:'£27.50/h',first:'G. Ionescu',claimedJob:null,claimState:'none',claimLabel:'NO CLAIM LINKED',claimNote:'No safe claim-to-call link found for the 19 Aug call.',summary:'Worker discussed dryliner work around E1/E1W at £27–28/h. He is busy now but open to offers depending on location and work type.',why:['Exact trade','E17 → E1W','Rate range aligns'],confidence:88},
  {id:18,day:'19 AUG',status:'followup',worker:'M. E.',workerTrade:'Dryliner',jobTrade:'Dryliner',workerPostcode:'E14…',second:'P. Jones',callTime:'19 Aug · 18:00 UK',callOutcome:'Follow-up',job:'Dryliner — E1W',jobPostcode:'E1W',rate:'£27.50/h',first:'G. Ionescu',claimedJob:null,claimState:'none',claimLabel:'NO CLAIM LINKED',claimNote:'No safe claim-to-call link found for the 19 Aug call.',summary:'Worker was offered central-London dryliner work at £29/h for 6–8 weeks. He is currently working but showed interest.',why:['Exact trade','East/Central London','Interested despite current work'],confidence:86},
  {id:19,day:'19 AUG',status:'followup',worker:'G. B.',workerTrade:'Dryliner',jobTrade:'Dryliner',workerPostcode:'E1…',second:'P. Jones',callTime:'19 Aug · 14:17 UK',callOutcome:'Follow-up',job:'Dryliner — E1W',jobPostcode:'E1W',rate:'£27.50/h',first:'G. Ionescu',claimedJob:null,claimState:'none',claimLabel:'NO CLAIM LINKED',claimNote:'No safe claim-to-call link found for the 19 Aug call.',summary:'Worker discussed a central-London dryliner role, works as a pair and negotiated toward £30/h before agreeing to reply on WhatsApp.',why:['Exact trade','E1 → E1W','Pair available'],confidence:87},
  {id:20,day:'19 AUG',status:'followup',worker:'A. M.',workerTrade:'Banksman / electrical skills',jobTrade:'Multi Trader',workerPostcode:'NW2…',second:'L. Constantin',callTime:'19 Aug · 17:41 UK',callOutcome:'Follow-up',job:'Multi Trader — N5',jobPostcode:'N5 1QN',rate:'£26/h',first:'G. Ionescu',claimedJob:null,claimState:'none',claimLabel:'NO CLAIM LINKED',claimNote:'No safe claim-to-call link found for the 19 Aug call.',summary:'Candidate confirmed interest in handyman-type work, availability, electrical qualifications, CSCS, banksman card, right to work and own tools.',why:['Multi-skilled profile','North London option','Tools + CSCS'],confidence:75}
];

const $ = s => document.querySelector(s);
const esc = (v='') => String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function badge(status){return status==='strong'?'<span class="role-badge primary-role">STRONG</span>':'<span class="role-badge alt-role">FOLLOW-UP</span>'}
function scoreClass(s){return s>=90?'score-strong':s>=75?'score-good':s>=50?'score-review':'score-low'}
function claimClass(x){return x.claimState==='at_call'?'claim-exact':x.claimState==='claimed_later'?'claim-later':'claim-none'}
function callRate(summary=''){const text=String(summary);const pound=text.match(/£\s?\d+(?:\.\d+)?(?:\s*[-–]\s*£?\d+(?:\.\d+)?)?\s*(?:\/h|\/hour|per hour|ph|pph)?/i);if(pound)return pound[0].replace(/\s+/g,' ');const day=text.match(/\b(\d{3})\s*(?:GBP|£)?\s*(?:per day|\/day)/i);return day?`£${day[1]}/day`:'—'}
function mini(label,value,cls=''){return `<div class="mini-field ${cls}"><span>${esc(label)}</span><strong>${esc(value||'—')}</strong></div>`}
function renderStats(rows){const d20=rows.filter(x=>x.day==='20 AUG').length,d19=rows.filter(x=>x.day==='19 AUG').length,claimed=rows.filter(x=>x.claimState==='at_call').length;$('#stats').innerHTML=[[rows.length,'Matches'],[d20,'20 Aug calls'],[d19,'19 Aug calls'],[claimed,'Claim-linked'],['19 + 20 Aug','Job window']].map(([n,l])=>`<div class="stat"><div class="num">${esc(n)}</div><div class="label">${esc(l)}</div></div>`).join('')}
function render(){const q=$('#searchInput').value.trim().toLowerCase();const status=$('#statusFilter').value;const rows=realCases.filter(x=>{const blob=[x.day,x.worker,x.workerTrade,x.jobTrade,x.workerPostcode,x.second,x.first,x.job,x.jobPostcode,x.rate,x.summary,x.claimedJob,x.claimLabel].join(' ').toLowerCase();return(!q||blob.includes(q))&&(status==='all'||x.status===status)});$('#caseCount').textContent=rows.length;renderStats(rows);$('#caseList').innerHTML=rows.map(x=>`<article class="match-card ${x.status}"><div class="match-topbar"><div class="match-id">#${x.id}</div><div class="match-title"><span class="day-pill">${esc(x.day)}</span> ${esc(x.workerTrade)} <span>↔</span> ${esc(x.jobTrade)}</div><div class="match-meta">${badge(x.status)}<div class="score ${scoreClass(x.confidence)}">${x.confidence}%</div></div></div><div class="compare-grid"><section class="side blue-side"><div class="side-title">BLUE CALL · ${esc(x.day)}</div>${mini('MUNCITOR',x.worker,'hero-mini')}${mini('MESERIE',x.workerTrade)}${mini('POSTCODE',x.workerPostcode)}${mini('SECOND',x.second,'second-mini')}${mini('ORA',x.callTime)}${mini('OUTCOME',x.callOutcome)}<div class="claim-panel ${claimClass(x)}"><span>CLAIM JOB</span><strong>${esc(x.claimedJob||x.claimLabel)}</strong><small>${esc(x.claimNote)}</small></div></section><div class="match-arrow">MATCH</div><section class="side job-side"><div class="side-title">JOB DASHBOARD · 19 + 20 AUG</div>${mini('JOB',x.job,'hero-mini')}${mini('MESERIE',x.jobTrade)}${mini('POSTCODE',x.jobPostcode)}${mini('FIRST',x.first,'first-mini')}${mini('RATE JOB',x.rate,'rate-mini')}${mini('RATE DIN APEL',callRate(x.summary),'accepted-mini')}</section></div><details class="summary-box"><summary><span>REZUMAT AI</span><b>${esc(x.summary)}</b></summary><div class="summary-full">${esc(x.summary)}</div></details><div class="why-row">${x.why.map(r=>`<span>${esc(r)}</span>`).join('')}</div></article>`).join('')||'<div class="empty">No matches.</div>'}
$('#searchInput').addEventListener('input',render);$('#statusFilter').addEventListener('change',render);render();