const realCases = [
  {id:1,status:'strong',worker:'V. C.',workerTrade:'Labourer',jobTrade:'Labourer',workerPostcode:'CR3…',workerPhone:'+44 •••• •• 5283',second:'F. Fabian',callTime:'18 Aug 2026 · 10:48 UK',callOutcome:'Interested',job:'Labourer — Croydon',jobPostcode:'CR28 / Croydon',rate:'£14.50/h',first:'N. Robert',summary:'Worker confirmed interest in labourer work around Croydon, said he lives in the area, has a Romanian driving licence and stated that the required documents are available. Details were to continue on WhatsApp.',why:['Exact trade: Labourer','Worker lives in the Croydon area','Explicit interest in the Blue call','Job Board vacancy is still open'],confidence:98},
  {id:2,status:'strong',worker:'M. N.',workerTrade:'Carpenter',jobTrade:'Carpenter / Joiner',workerPostcode:'SW17…',workerPhone:'+44 •••• •• 5231',second:'Vania',callTime:'18 Aug 2026 · 09:46 UK',callOutcome:'Follow-up',job:'Carpenter / Joiner — SW17',jobPostcode:'SW17 9JA',rate:'£26/h',first:'Alexandra',summary:'Worker was contacted about a carpenter job starting the next day and asked for the postcode on WhatsApp so the route could be checked. Blue profile confirms Carpenter and the profile postcode is SW17, the same district as the current Job Board vacancy.',why:['Exact Carpenter trade','Worker postcode is SW17','Job postcode is SW17 9JA','Worker requested job details before confirming'],confidence:94},
  {id:3,status:'strong',worker:'A. P.',workerTrade:'Dryliner',jobTrade:'Dryliner',workerPostcode:'SW19…',workerPhone:'+44 •••• •• 2489',second:'A. Robin',callTime:'18 Aug 2026 · 11:23 UK',callOutcome:'Follow-up',job:'Dryliner — SW16',jobPostcode:'SW16 4LP',rate:'£25/h',first:'N. Robert',summary:'Worker discussed a dryliner role in London. He said the offered rate was a little below market and that he may be available from the following week together with a colleague. He requested a follow-up call.',why:['Exact Dryliner trade','SW19 to SW16 is a close South London match','Worker remains open to the role','Rate and start date need reconfirmation'],confidence:88},
  {id:4,status:'followup',worker:'V. G.',workerTrade:'Dryliner',jobTrade:'Dryliner',workerPostcode:'BR7…',workerPhone:'+44 •••• •• 7788',second:'C. Silver',callTime:'18 Aug 2026 · 11:15 UK',callOutcome:'Follow-up',job:'Dryliner — SW16',jobPostcode:'SW16 4LP',rate:'£25/h',first:'N. Robert',summary:'Worker was called about a dryliner job in London and requested the details on WhatsApp so he could check them and call back. Blue profile confirms Dryliner as the primary trade.',why:['Exact Dryliner trade','London-area journey is plausible','Worker asked to review the details','Explicit acceptance is still required'],confidence:84},
  {id:5,status:'followup',worker:'M. T.',workerTrade:'Handyman',jobTrade:'Multi Trader',workerPostcode:'N13…',workerPhone:'+44 •••• •• 1564',second:'L. Constantin',callTime:'18 Aug 2026 · 11:02 UK',callOutcome:'Follow-up',job:'Multi Trader — E17',jobPostcode:'E17',rate:'To confirm',first:'N. Robert',summary:'Worker discussed a long-term multi-trader role and talked through carpentry and drylining tasks. He showed reservations about some plasterboard work, so exact task scope needs confirming before the worker is sent.',why:['Handyman is closely related to Multi Trader','North/East London journey is reasonable','Conversation supports multi-trade experience','Specific task scope still needs verification'],confidence:81},
  {id:6,status:'followup',worker:'S. B.',workerTrade:'Carpenter',jobTrade:'Fire Stopper',workerPostcode:'SM6…',workerPhone:'+44 •••• •• 0887',second:'R. Gomez',callTime:'18 Aug 2026 · 09:27 UK',callOutcome:'Follow-up',job:'Fire Stopper — SE1',jobPostcode:'SE1 7LR',rate:'£25/h',first:'N. Robert',summary:'Worker reported 11 years of carpentry experience including fire-door fitting and finishing. A firestopping opportunity was discussed and both sides agreed to continue by message.',why:['Relevant fire-door experience','South London geography','Firestop work was discussed in the call','Batt and mastic experience must still be confirmed'],confidence:77},
  {id:7,status:'followup',worker:'A. S.',workerTrade:'Carpenter',jobTrade:'Carpenter / Joiner',workerPostcode:'RH10…',workerPhone:'+44 •••• •• 3214',second:'C. Mihai',callTime:'18 Aug 2026 · 10:42 UK',callOutcome:'Follow-up',job:'Carpenter / Joiner — SW17',jobPostcode:'SW17 9JA',rate:'£26/h',first:'Alexandra',summary:'Worker was contacted about a carpenter role and asked to continue through WhatsApp because he was busy. Blue profile confirms Carpenter as the primary trade.',why:['Exact Carpenter trade','Worker requested a WhatsApp follow-up','Current Job Board vacancy is active','Travel from RH10 to SW17 needs confirmation'],confidence:76},
  {id:8,status:'followup',worker:'A. C.',workerTrade:'Carpenter',jobTrade:'Carpenter',workerPostcode:'RM9…',workerPhone:'+44 •••• •• 2487',second:'Nicoleta',callTime:'18 Aug 2026 · 10:01 UK',callOutcome:'Follow-up',job:'Carpenter — W14',jobPostcode:'W14',rate:'£26/h',first:'N. Robert',summary:'A real Blue call was made regarding a carpenter opportunity. The worker was not directly available on the phone; the person answering said the worker would receive the recruiter’s number and call back if interested.',why:['Exact Carpenter trade','Real active W14 carpenter vacancy','No direct worker confirmation yet','Wait for callback before sending to First'],confidence:71},
  {id:9,status:'blocked',worker:'E. M.',workerTrade:'Labourer',jobTrade:'Labourer',workerPostcode:'LE12…',workerPhone:'+44 •••• •• 7446',second:'Adam M',callTime:'18 Aug 2026 · 11:17 UK',callOutcome:'Follow-up',job:'Labourer — LE5',jobPostcode:'LE5',rate:'£16.25/h',first:'N. Robert',summary:'Worker was contacted for a labourer role around LE5. He said he was on holiday and would return on Monday. Trade and area are good, but he should not be sent as an immediate placement until availability is reconfirmed.',why:['Exact Labourer trade','Leicester-area match','Worker unavailable at time of call','Recheck availability on return'],confidence:68},
  {id:10,status:'blocked',worker:'P. P.',workerTrade:'Labourer',jobTrade:'Multi Trader',workerPostcode:'Manchester preference',workerPhone:'+44 •••• •• 2476',second:'G. Ionescu',callTime:'18 Aug 2026 · 10:58 UK',callOutcome:'Follow-up',job:'Multi Trader — E17',jobPostcode:'E17',rate:'To confirm',first:'N. Robert',summary:'Worker was offered a London multi-trader role but explicitly said he wants work only around Manchester, Leeds or Sheffield. The system blocks this London match despite superficial construction-trade similarity.',why:['Location conflict','Worker explicitly rejected London','Primary trade does not support an automatic Multi Trader match','Do not send to First'],confidence:15}
];

const $ = s => document.querySelector(s);
const esc = (v='') => String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function badge(status){if(status==='strong')return '<span class="role-badge primary-role">STRONG MATCH</span>';if(status==='followup')return '<span class="role-badge alt-role">FOLLOW-UP</span>';return '<span class="role-badge" style="background:#fef2f2;color:#b91c1c">BLOCKED / NOT NOW</span>'}
function scoreClass(s){return s>=90?'score-strong':s>=75?'score-good':s>=50?'score-review':'score-low'}
function renderStats(rows){const strong=rows.filter(x=>x.status==='strong').length,follow=rows.filter(x=>x.status==='followup').length,blocked=rows.filter(x=>x.status==='blocked').length;$('#stats').innerHTML=[[rows.length,'Real situations'],[strong,'Strong matches'],[follow,'Follow-up'],[blocked,'Blocked'],['20 Aug','Matching refresh']].map(([n,l])=>`<div class="stat"><div class="num">${esc(n)}</div><div class="label">${esc(l)}</div></div>`).join('')}
function render(){const q=$('#searchInput').value.trim().toLowerCase();const status=$('#statusFilter').value;const rows=realCases.filter(x=>{const blob=[x.worker,x.workerTrade,x.jobTrade,x.workerPostcode,x.workerPhone,x.second,x.first,x.job,x.jobPostcode,x.rate,x.summary,x.status].join(' ').toLowerCase();return(!q||blob.includes(q))&&(status==='all'||x.status===status)});$('#caseCount').textContent=rows.length;renderStats(rows);$('#caseList').innerHTML=rows.map(x=>`<article class="top10-card"><div class="top10-rank">#${x.id}</div><div class="top10-main"><div class="top10-title"><strong>${esc(x.worker)}</strong><span>→</span><strong>${esc(x.job)}</strong></div><div class="ownership-row compact"><div class="owner-box first-box"><span class="owner-label">FIRST · POSTED THE JOB</span><strong>${esc(x.first)}</strong></div><div class="owner-box second-box"><span class="owner-label">SECOND · MADE THE BLUE CALL</span><strong>${esc(x.second)}</strong></div></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:8px;margin:10px 0"><div class="owner-box"><span class="owner-label">WORKER NAME</span><strong>${esc(x.worker)}</strong></div><div class="owner-box"><span class="owner-label">WORKER MESERIE</span><strong>${esc(x.workerTrade)}</strong></div><div class="owner-box"><span class="owner-label">JOB TRADE</span><strong>${esc(x.jobTrade)}</strong></div><div class="owner-box"><span class="owner-label">WORKER POSTCODE</span><strong>${esc(x.workerPostcode)}</strong></div><div class="owner-box"><span class="owner-label">WORKER NUMBER · MASKED PUBLIC</span><strong>${esc(x.workerPhone)}</strong></div><div class="owner-box"><span class="owner-label">BLUE CALL DATE / TIME</span><strong>${esc(x.callTime)}</strong></div></div><div class="job-meta" style="margin-bottom:8px"><span class="mini">Job postcode: ${esc(x.jobPostcode)}</span><span class="mini">Outcome: ${esc(x.callOutcome)}</span><span class="mini">Rate: ${esc(x.rate)}</span></div><div class="summary"><strong>Real call summary:</strong> ${esc(x.summary)}</div><div class="reasons">${x.why.map(r=>`<span class="reason ${x.status==='blocked'?'bad':x.status==='strong'?'ok':'info'}">${esc(r)}</span>`).join('')}</div></div><div class="top10-side">${badge(x.status)}<div class="score ${scoreClass(x.confidence)}">${x.confidence}<small>CONFIDENCE</small></div></div></article>`).join('')||'<div class="empty">No real situations match these filters.</div>'}
$('#searchInput').addEventListener('input',render);$('#statusFilter').addEventListener('change',render);render();
