const realCases = [
  {id:1,status:'strong',worker:'V. C.',workerTrade:'Labourer',workerPostcode:'CR3…',second:'F. Fabian',callTime:'18 Aug 2026 · 09:48 UTC',callOutcome:'Interested',job:'Labourer — Croydon',jobPostcode:'CR28 / Croydon',rate:'£14.50/h',first:'N. Robert',summary:'Worker confirmed interest in labourer work around Croydon, said he lives in the area, has a Romanian driving licence and stated that the required documents are available. Details were to continue on WhatsApp.',why:['Exact primary trade','Worker is in Croydon area','Explicit interest in call','Real open Job Board vacancy'],confidence:98},
  {id:2,status:'followup',worker:'A. P.',workerTrade:'Dryliner',workerPostcode:'SW19…',second:'A. Robin',callTime:'18 Aug 2026 · 10:23 UTC',callOutcome:'Follow-up',job:'Dryliner — SW16',jobPostcode:'SW16 4LP',rate:'£25/h',first:'N. Robert',summary:'Worker discussed a dryliner role in London. He said the rate offered in the call was slightly below market and that he may be available from the following week together with a colleague. He requested a follow-up call.',why:['Exact primary trade','South London geography','Availability is delayed','Rate needs reconfirmation'],confidence:86},
  {id:3,status:'followup',worker:'V. G.',workerTrade:'Dryliner',workerPostcode:'BR7…',second:'C. Silver',callTime:'18 Aug 2026 · 10:15 UTC',callOutcome:'Follow-up',job:'Dryliner — SW16',jobPostcode:'SW16 4LP',rate:'£25/h',first:'N. Robert',summary:'Worker was called about a dryliner job in London and asked for the details on WhatsApp so he could check them and call back. His Blue profile also identifies Dryliner as the primary trade.',why:['Exact primary trade','London-area travel possible','Worker asked for details','Needs explicit acceptance'],confidence:82},
  {id:4,status:'blocked',worker:'E. M.',workerTrade:'Labourer',workerPostcode:'LE12…',second:'A. M.',callTime:'18 Aug 2026 · 10:17 UTC',callOutcome:'Follow-up',job:'Labourer — LE5',jobPostcode:'LE5',rate:'£16.25/h',first:'N. Robert',summary:'Worker was contacted for a labourer role around LE5. He said he was on holiday and would return on Monday, so this should not be sent as an immediate placement.',why:['Exact trade','Leicester-area job','Candidate unavailable now','Recheck on return'],confidence:79},
  {id:5,status:'followup',worker:'M. T.',workerTrade:'Handyman',workerPostcode:'N13…',second:'L. Constantin',callTime:'18 Aug 2026 · 10:02 UTC',callOutcome:'Follow-up',job:'Multi Trader — E17',jobPostcode:'E17',rate:'To confirm',first:'N. Robert',summary:'Worker discussed a long-term multi-trader role and talked through carpentry and drylining tasks. He showed reservations about some plasterboard work, so skill scope must be confirmed before sending.',why:['Related Handyman / Multi Trader trade','North/East London travel reasonable','Conversation supports multi-trade work','Task scope needs verification'],confidence:78},
  {id:6,status:'followup',worker:'S. B.',workerTrade:'Carpenter',workerPostcode:'SM6…',second:'R. Gomez',callTime:'18 Aug 2026 · 08:27 UTC',callOutcome:'Follow-up',job:'Fire Stopper — SE1',jobPostcode:'SE1 7LR',rate:'£25/h',first:'N. Robert',summary:'Worker reported 11 years of carpentry experience including fire-door fitting and finishing. A firestopping opportunity was discussed and both sides agreed to continue by message. This is a skill-adjacent match, not an automatic trade match.',why:['Relevant fire-door experience','South London proximity','Firestop role discussed','Primary trade is Carpenter — verify batt/mastic experience'],confidence:74},
  {id:7,status:'followup',worker:'A. S.',workerTrade:'Carpenter',workerPostcode:'RH10…',second:'C. Mihai',callTime:'18 Aug 2026 · 09:42 UTC',callOutcome:'Follow-up',job:'Carpenter / Joiner — SW17',jobPostcode:'SW17 9JA',rate:'£26/h',first:'A. (First)',summary:'Worker was contacted about a carpenter role and asked to continue through WhatsApp because he was busy. His Blue profile confirms Carpenter as the primary trade.',why:['Exact carpenter trade','South-East/South London travel to verify','Worker requested follow-up','Rate/location need final confirmation'],confidence:76},
  {id:8,status:'followup',worker:'A. C.',workerTrade:'Carpenter',workerPostcode:'RM9…',second:'Nicoleta',callTime:'18 Aug 2026 · 09:01 UTC',callOutcome:'Follow-up',job:'Carpenter — W14',jobPostcode:'W14',rate:'£26/h',first:'N. Robert',summary:'A real Blue call was made regarding a carpenter opportunity. The worker was not directly available on the phone; the person answering said the worker would receive the recruiter’s number and call back if interested.',why:['Exact carpenter trade','Real W14 carpenter vacancy','No direct worker confirmation yet','Wait for callback before sending'],confidence:69},
  {id:9,status:'followup',worker:'I. B.',workerTrade:'Carpenter',workerPostcode:'SW4…',second:'Blue agent',callTime:'18 Aug 2026 · 08:44 UTC',callOutcome:'Follow-up',job:'Carpenter / Joiner — SW17',jobPostcode:'SW17 9JA',rate:'£26/h',first:'A. (First)',summary:'Worker was contacted about a carpenter role and asked for the details on WhatsApp, saying he would respond shortly after reviewing them. Blue profile confirms Carpenter.',why:['Exact carpenter trade','South London location','Requested WhatsApp details','Needs explicit acceptance'],confidence:83},
  {id:10,status:'blocked',worker:'P. P.',workerTrade:'Labourer',workerPostcode:'Manchester preference',second:'G. Ionescu',callTime:'18 Aug 2026 · 09:58 UTC',callOutcome:'Follow-up',job:'Multi Trader — E17',jobPostcode:'E17',rate:'To confirm',first:'N. Robert',summary:'Worker was offered a London multi-trader role but explicitly said he wants work only around Manchester, Leeds or Sheffield. The system must block this London match despite any superficial trade similarity.',why:['Location conflict','Worker explicitly rejected London','Primary trade does not support auto-match','Do not send to First'],confidence:15}
];

const $ = s => document.querySelector(s);
const esc = (v='') => String(v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function badge(status){if(status==='strong')return '<span class="role-badge primary-role">STRONG MATCH</span>';if(status==='followup')return '<span class="role-badge alt-role">FOLLOW-UP</span>';return '<span class="role-badge" style="background:#fef2f2;color:#b91c1c">BLOCKED / NOT NOW</span>'}
function scoreClass(s){return s>=90?'score-strong':s>=75?'score-good':s>=50?'score-review':'score-low'}
function renderStats(rows){const strong=rows.filter(x=>x.status==='strong').length,follow=rows.filter(x=>x.status==='followup').length,blocked=rows.filter(x=>x.status==='blocked').length;$('#stats').innerHTML=[[rows.length,'Real situations'],[strong,'Strong matches'],[follow,'Follow-up'],[blocked,'Blocked'],['Blue + Job Board','Sources']].map(([n,l])=>`<div class="stat"><div class="num">${esc(n)}</div><div class="label">${esc(l)}</div></div>`).join('')}
function render(){const q=$('#searchInput').value.trim().toLowerCase();const status=$('#statusFilter').value;const rows=realCases.filter(x=>{const blob=[x.worker,x.workerTrade,x.workerPostcode,x.second,x.first,x.job,x.jobPostcode,x.rate,x.summary,x.status].join(' ').toLowerCase();return(!q||blob.includes(q))&&(status==='all'||x.status===status)});$('#caseCount').textContent=rows.length;renderStats(rows);$('#caseList').innerHTML=rows.map(x=>`<article class="top10-card"><div class="top10-rank">#${x.id}</div><div class="top10-main"><div class="top10-title"><strong>${esc(x.worker)}</strong><span>→</span><strong>${esc(x.job)}</strong></div><div class="top10-sub">Worker trade: ${esc(x.workerTrade)} · Worker postcode: ${esc(x.workerPostcode)} · Job postcode: ${esc(x.jobPostcode)}</div><div class="ownership-row compact"><div class="owner-box first-box"><span class="owner-label">FIRST · POSTED THE JOB</span><strong>${esc(x.first)}</strong></div><div class="owner-box second-box"><span class="owner-label">SECOND · MADE THE BLUE CALL</span><strong>${esc(x.second)}</strong></div></div><div class="job-meta" style="margin-bottom:8px"><span class="mini">Blue call: ${esc(x.callTime)}</span><span class="mini">Outcome: ${esc(x.callOutcome)}</span><span class="mini">Rate: ${esc(x.rate)}</span></div><div class="summary"><strong>Real call summary:</strong> ${esc(x.summary)}</div><div class="reasons">${x.why.map(r=>`<span class="reason ${x.status==='blocked'?'bad':x.status==='strong'?'ok':'info'}">${esc(r)}</span>`).join('')}</div></div><div class="top10-side">${badge(x.status)}<div class="score ${scoreClass(x.confidence)}">${x.confidence}<small>CONFIDENCE</small></div></div></article>`).join('')||'<div class="empty">No real situations match these filters.</div>'}
$('#searchInput').addEventListener('input',render);$('#statusFilter').addEventListener('change',render);render();
